.travis.yml

This is an attempt to make Travis only run once per PR commit.

Dup travis test fix

---

config.example.js
package-lock.json
package.json
src/app/plugins/openstack/actions/session.js
src/app/util/http.js
src/app/util/registry.js
src/openstack-simulator/api/keystone.js
src/openstack-simulator/context.js
src/openstack-simulator/helpers.js
src/openstack-simulator/main.js
src/openstack-simulator/middleware.js
src/openstack-simulator/models/ActiveModel.js
src/openstack-simulator/models/Region.js
src/openstack-simulator/models/Role.js
src/openstack-simulator/models/Tenant.js
src/openstack-simulator/models/Token.js
src/openstack-simulator/models/User.js
src/openstack-simulator/models/__tests__/ActiveModel.test.js
src/openstack-simulator/models/__tests__/Token.test.js
src/openstack-simulator/presets/base.js
src/openstack-simulator/server.js

This is the start of the new version of the OpenStack simulator.
It could use a little better test coverage but it is working with basic session logins right now.

Create basic OpenStack API simulator

---

.eslintrc
package-lock.json
package.json
src/openstack-simulator/__tests__/helpers.test.js
src/openstack-simulator/context.js
src/openstack-simulator/helpers.js
src/openstack-simulator/main.js
src/openstack-simulator/models/Role.js
src/openstack-simulator/models/User.js
src/openstack-simulator/models/__tests__/ActiveModel.test.js
src/openstack-simulator/models/__tests__/Role.test.js
src/openstack-simulator/models/__tests__/Token.test.js
src/openstack-simulator/models/__tests__/User.test.js

Just more unit tests for the simulator.  No new functionality.

More unit tests for the simulator

---

.eslintrc
.gitignore
README.md
package-lock.json
package.json
stories/config.js
stories/index.js

This adds support for Storybook so we can develop components in isolation and control the state that is feed to them.
There are also some minor cleanups here.

Add basic setup for Storybook

---

package-lock.json
package.json
src/app/core/common/ConfirmationDialog.js
src/app/plugins/openstack/components/LoginPage.js
src/app/plugins/openstack/components/common/EnhancedTableToolbar.js
src/app/plugins/openstack/components/common/ListTable.js
src/app/plugins/openstack/components/users/AddUserPage.js
src/app/plugins/openstack/components/users/UsersList.js
src/app/plugins/openstack/components/users/UsersListContainer.js
src/app/plugins/openstack/reducers/users.js
src/openstack-simulator/main.js
src/openstack-simulator/models/User.js
src/openstack-simulator/presets/dev.js
src/stories/common/ConfirmationDialog.stories.js
src/stories/users/addUser.stories.js
src/stories/users/listUsers.stories.js

Small fixes for user management

---

src/app/plugins/openstack/actions/tenants.js
src/app/plugins/openstack/actions/users.js
src/app/plugins/openstack/api/keystone.js
src/app/plugins/openstack/components/flavors/FlavorsListContainer.js
src/app/plugins/openstack/components/tenants/AddTenantForm.js
src/app/plugins/openstack/components/tenants/AddTenantPage.js
src/app/plugins/openstack/components/tenants/TenantsList.js
src/app/plugins/openstack/components/tenants/TenantsListContainer.js
src/app/plugins/openstack/components/users/UsersListContainer.js
src/app/plugins/openstack/index.js
src/app/plugins/openstack/reducers/tenants.js
src/app/plugins/openstack/reducers/users.js
src/openstack-simulator/api/keystone/deleteProject.js
src/openstack-simulator/api/keystone/index.js
src/openstack-simulator/api/keystone/postProject.js
src/openstack-simulator/presets/dev.js
src/stories/tenants/addTenant.stories.js
src/stories/tenants/fakeTenant.js
src/stories/tenants/listTenants.stories.js

Just fleshing out more functionality for Users, Tenants, and Flavors.

Lots of misc functionality for tenants/users/flavors

---

src/app/plugins/openstack/components/tenants/AddTenantPage.js
src/app/plugins/openstack/components/tenants/TenantsListPage.js
src/app/plugins/openstack/components/tenants/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/UserManagement.graphql
src/graphql/openstack/schemas/userManagement.js
src/server/context.js

Here are some more of the patterns for GraphQL.  It has full CRUD for tenants in GraphQL working now.  This can serve as an example for the other models.

Add more GraphQL functionality for tenants

---

src/app/plugins/openstack/components/flavors/AddFlavorForm.js
src/app/plugins/openstack/components/flavors/AddFlavorPage.js
src/app/plugins/openstack/components/flavors/FlavorsListContainer.js
src/app/plugins/openstack/components/flavors/FlavorsListPage.js
src/app/plugins/openstack/components/flavors/actions.js
src/app/plugins/openstack/components/tenants/AddTenantPage.js
src/app/plugins/openstack/components/tenants/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/Flavor.graphql
src/graphql/openstack/schemas/flavors.js
src/server/context.js
src/server/models/Flavor.js

This PR converts Flavors from using redux to GraphQL.  I also added the corresponding GraphQL endpoints on the server.

Full CRUD of flavors in GraphQL

---

package-lock.json
package.json
src/app/core/common/__tests__/formatter.test.js
src/app/core/common/formatters.js

Fix formatter.js with moment.js and add tests.

Fix formatter.js to work for local time.

---

src/app/plugins/openstack/components/LoginPage.js
src/stories/UI/loginPage.js
src/stories/UI/loginPage.stories.js

Add new style to current login form.

Styled Login Form

---

config.example.js
package-lock.json
package.json
src/openstack-client/Keystone.js
src/openstack-client/OpenstackClient.js
src/openstack-client/__tests__/Keystone.test.js
src/openstack-client/__tests__/OpenstackClient.test.js
src/openstack-client/index.js
src/openstack-client/openstack-client.md

I'm working on pulling the OpenStack REST API into its own library.  I'm structuring it is such a way to be consumed as a library by other projects and not have any coupling with the UI.  That being said, it will be opinionated and make things more convenient.  It abstracts away some of the complexity and maintains its own state.
It's currently a work in progress but I want to put it out there to get some early feedback.

Openstack client API library

---

package-lock.json
package.json
src/app/App.js
src/app/core/common/ConfirmationDialog.js
src/app/core/common/EnhancedTableHead.js
src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js
src/app/core/common/Navbar.js
src/app/plugins/kubernetes/components/clusters/AddClusterForm.js
src/app/plugins/openstack/components/LoginPage.js
src/app/plugins/openstack/components/flavors/AddFlavorForm.js
src/app/plugins/openstack/components/networks/AddNetworkForm.js
src/app/plugins/openstack/components/tenants/AddTenantForm.js
src/app/plugins/openstack/components/users/AddUserForm.js
src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/stories/UI/loginPage.js

* Remove old version of material-ui & material-ui-icons
* Everything works well with new version.

Remove old version of material-ui & material-ui-icons

---

src/app/core/common/CRUDListContainer.js
src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js
src/app/plugins/openstack/components/users/UpdateUserForm.js
src/app/plugins/openstack/components/users/UpdateUserPage.js
src/app/plugins/openstack/components/users/UsersList.js
src/app/plugins/openstack/components/users/UsersListContainer.js
src/app/plugins/openstack/components/users/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/UserManagement.graphql
src/graphql/openstack/schemas/userManagement.js
src/server/context.js
src/server/helpers.js
src/server/models/User.js

Added user update

---

src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/app/plugins/openstack/components/volumes/UpdateVolumeForm.js
src/app/plugins/openstack/components/volumes/UpdateVolumePage.js
src/app/plugins/openstack/components/volumes/VolumesList.js
src/app/plugins/openstack/components/volumes/VolumesListContainer.js
src/app/plugins/openstack/components/volumes/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/Volume.graphql
src/graphql/openstack/schemas/volumes.js
src/server/context.js
src/server/models/Volume.js

* Update `Volume` schema
* Add UpdateVolumePage

Add UpdateVolumePage

---

src/app/plugins/openstack/components/glanceimages/GlanceImageList.js
src/app/plugins/openstack/components/glanceimages/GlanceImageListContainer.js
src/app/plugins/openstack/components/glanceimages/UpdateGlanceImageForm.js
src/app/plugins/openstack/components/glanceimages/UpdateGlanceImagePage.js
src/app/plugins/openstack/components/glanceimages/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/GlanceImage.graphql
src/graphql/openstack/schemas/glanceImages.js
src/server/context.js
src/server/models/GlanceImage.js

* Update glance image schemas.
* Add glance image update page.

Add glance image update

---

src/app/core/common/EnhancedTableHead.js
src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js

* If all items on the current page are deleted, it will go back to the pervious page.
* `SelectAll` will get all the items on the current page.
* Ensure the height of L`ListTable` won't change frequently.
* Merge `edit` and `delete` button to toolbar.
* Always show `PaginationControl` to fix the height.
* Change the color to `primary`

Fix small issues in ListTable

---

src/app/plugins/openstack/components/networks/NetworksList.js
src/app/plugins/openstack/components/networks/UpdateNetworkForm.js
src/app/plugins/openstack/components/networks/UpdateNetworkPage.js
src/app/plugins/openstack/components/networks/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/schemas/Network.graphql
src/graphql/openstack/schemas/networks.js
src/server/context.js
src/server/models/Network.js
src/server/models/__tests__/Network.test.js
src/server/presets/dev.js

* Update network schemas.
* Add network update page.

Add network upate.

---

src/app/plugins/openstack/components/glanceimages/AddGlanceImagePage.js

Remove unused checkboxes in add-image page.

Remove unused checkboxes.

---

package-lock.json
package.json

I was working on another PR branch and I was seeing very weird issues with `npm install` not installing modules compatible with tests.  After spending over an hour debugging it I was able to get exactly the same `package.json` working if I rebuilt it directly from `master`.  I'm going to overwrite my branch and rebase it with this once it is merged into master.

Upgrade modules needed for testing

---

src/jsconfig.json

* Remove error of _[ts] Experimental suport for decorators is a feature that is subject to chang in a future release._

Remove decorator error.

---

src/app/plugins/openstack/components/routers/AddRouterForm.js
src/app/plugins/openstack/components/routers/AddRouterPage.js
src/app/plugins/openstack/components/routers/RoutersList.js
src/app/plugins/openstack/components/routers/RoutersListContainer.js
src/app/plugins/openstack/components/routers/RoutersListPage.js
src/app/plugins/openstack/components/routers/UpdateRouterForm.js
src/app/plugins/openstack/components/routers/UpdateRouterPage.js
src/app/plugins/openstack/components/routers/actions.js
src/app/plugins/openstack/index.js
src/graphql/openstack/index.js
src/graphql/openstack/schemas/Router.graphql
src/graphql/openstack/schemas/routers.js
src/server/api/neutron/deleteRouter.js
src/server/api/neutron/getRouters.js
src/server/api/neutron/index.js
src/server/api/neutron/postRouter.js
src/server/context.js
src/server/models/Router.js
src/server/models/__tests__/Router.test.js
src/server/presets/dev.js
src/stories/routers/addRouter.stories.js
src/stories/routers/fakeRouter.js
src/stories/routers/listRouters.stories.js

Basic routers functionality. Need to add api endpoints later as well as the actual router data linked to networks

Added basic router functionality in UI and simulator

---

src/app/App.js
src/app/app.css
src/app/core/common/ListTable.js
src/app/core/common/Navbar.js

Looking for suggestions regarding the showNavMenu and showNavBar stuff (left commented code in the review for easy reference) -- are these still needed? Which views with showNavBar be false for, maybe login?

Persistent navbar

---

src/app/core/common/Navbar.js
src/app/core/globals.js
src/app/plugins/openstack/components/LoginPage.js

Add logo to navbar and change menu icon color.

---

src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/app/plugins/openstack/components/volumes/AddVolumePage.js
src/app/plugins/openstack/components/volumes/StorageIndex.js
src/app/plugins/openstack/components/volumes/UpdateVolumeForm.js
src/app/plugins/openstack/components/volumes/UpdateVolumePage.js
src/app/plugins/openstack/components/volumes/VolumesListContainer.js
src/app/plugins/openstack/components/volumes/VolumesListPage.js
src/app/plugins/openstack/index.js

Add tabs to Volume page.

---

src/app/App.js
src/app/core/common/Navbar.js
src/app/plugins/openstack/actions/login.js
src/app/plugins/openstack/actions/session.js
src/app/plugins/openstack/components/LogoutPage.js
src/app/plugins/openstack/index.js
src/app/plugins/openstack/reducers/login.js

I added the ability to log out of the UI.
I also changed `App.js` so that it only renders the `Navbar` if the user is logged in.

Implement log out functionality

---

src/app/core/common/Avatar.js
src/app/core/common/Navbar.js
src/app/core/common/Selector.js

Add Region & Tenant selectors (mockup).

---

src/app/App.js

Simple fix to make session recovery work again on page load.

Restore session on page load

---

src/app/core/common/ProgressCard.js
src/app/core/common/ProgressCardList.js
src/app/core/common/formatters.js
src/app/plugins/openstack/components/DashboardPage.js
src/app/plugins/openstack/components/networks/NetworksListPage.js

Add ProgressCardList & ProgressCard component

---

src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js
src/app/plugins/openstack/components/api-access/ApiAccessList.js
src/app/plugins/openstack/components/flavors/FlavorsList.js
src/app/plugins/openstack/components/glanceimages/GlanceImageList.js
src/app/plugins/openstack/components/networks/NetworksList.js
src/app/plugins/openstack/components/routers/RoutersList.js
src/app/plugins/openstack/components/tenants/TenantsList.js
src/app/plugins/openstack/components/users/UsersList.js
src/app/plugins/openstack/components/volumes/VolumesList.js

Add search bar to list-table

---

src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js

Add clear button to search bar

---

src/graphql/openstack/schemas/userManagement.js
src/openstack-client/Keystone.js
src/openstack-client/Nova.js
src/openstack-client/OpenstackClient.js
src/openstack-client/__tests__/Nova.test.js
src/openstack-client/helpers.js
src/server/context/rest.js
src/server/context/simulator.js
src/server/presets/dev.js

Adds more REST APIs:
* Improved tenant support
* Improved users support
* Added Flavors CRUD

Add more REST APIs to context

---

src/app/core/common/EnhancedTableToolbar.js
src/app/core/common/ListTable.js
src/app/core/common/Navbar.js
src/app/core/common/SearchBar.js
src/app/core/common/Selector.js

Selector & SearchBar

---

src/app/core/common/Alert.js
src/app/plugins/openstack/components/LoginPage.js

Not the prettiest but we can tweak it more if anyone has suggestions.  I created an `<Alert>` component that behaves similar to the `<Snackbar>`.  I originally tried using it but it's not possible to change the width of it to fit inline.

Show error alert on bad login attempts

---

src/app/core/common/ProgressTracker.js
src/app/core/common/Wizard.js
src/app/core/common/WizardStep.js
src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/stories/common/ProgressTracker.stories.js
src/stories/common/fakeProgressTrackerItem.js

I was thinking of adding something to allow changing the activeStep in storybook, but then I thought about it and I'd only want to add it if it's necessary

Added progress tracker

---

src/app/core/common/Navbar.js
src/app/plugins/openstack/components/volumes/StorageIndex.js

Fixed typos

---

src/openstack-client/Nova.js

API without /detail only gives you id and name

Get flavor details instead of simple flavor info in openstack client

---

src/app/core/common/AnimateValues.js
src/app/core/common/dashboard_graphs/ServersGraph.js
src/app/core/common/dashboard_graphs/StorageGraph.js
src/app/core/common/dashboard_graphs/SvgArc.js
src/app/core/common/svg-helpers.js
src/stories/common/AnimateValues.stories.js

This creates an `<AnimateValues>` HOC for doing animations.
Ex:
```javascript
const calcStyle = ({ width }) => ({
width: `${width}px`,
height: '100px',
border: '1px solid #000',
backgroundColor: '#fcc',
})
<AnimateValues values={{ width: [0, 500] }} duration={3000}>
{values => (
<div style={calcStyle(values)}>
<pre>{JSON.stringify(values, null, 4)}</pre>
</div>
)}
</AnimateValues>
```
I also converted `<SvgArc>` to use it.

Create AnimateValues helper HOC for SvgArc

---

src/app/core/AppContext.js
src/app/core/DataLoader.js
src/app/core/common/Navbar.js
src/app/core/common/Selector.js
src/app/plugins/openstack/components/SessionManager.js
src/app/plugins/openstack/components/tenants/TenantChooser.js
src/app/plugins/openstack/components/tenants/actions.js
src/app/static/ui/index.html
src/openstack-client/Keystone.js

Still seems to be an issue when switching tenants that there are authorization errors.

TenantChooser

---

src/app/core/AppContext.js
src/app/core/DataUpdater.js
src/app/plugins/openstack/components/volumes/StorageIndex.js
src/app/plugins/openstack/components/volumes/UpdateVolumeSnapshotForm.js
src/app/plugins/openstack/components/volumes/UpdateVolumeSnapshotPage.js
src/app/plugins/openstack/components/volumes/VolumeSnapshotsList.js
src/app/plugins/openstack/components/volumes/VolumeSnapshotsListContainer.js
src/app/plugins/openstack/components/volumes/VolumeSnapshotsListPage.js
src/app/plugins/openstack/components/volumes/actions.js
src/app/plugins/openstack/index.js

This is current a WIP.
TODO:
* Need ability to switch the active tenant so I can see existing snapshots.
* Add / Delete / Update functionality still needed

Volume snapshots

---

src/app/core/common/EnhancedTableHead.js
src/app/core/common/ListTable.js
src/app/core/common/MoreMenu.js
src/app/plugins/kubernetes/components/clusters/ClustersList.js
src/app/plugins/openstack/components/flavors/FlavorsList.js
src/app/plugins/openstack/components/floatingips/FloatingIpsList.js
src/app/plugins/openstack/components/hosts/HostsList.js
src/app/plugins/openstack/components/images/ImageList.js
src/app/plugins/openstack/components/instances/InstancesList.js
src/app/plugins/openstack/components/networks/NetworksList.js
src/app/plugins/openstack/components/routers/RoutersList.js
src/app/plugins/openstack/components/sshkeys/SshKeysList.js
src/app/plugins/openstack/components/tenants/TenantsList.js
src/app/plugins/openstack/components/users/UsersList.js
src/app/plugins/openstack/components/volumes/VolumeSnapshotsList.js
src/app/plugins/openstack/components/volumes/VolumeTypesList.js
src/app/plugins/openstack/components/volumes/VolumesList.js
src/stories/common/ListTable.stories.js
src/stories/common/MoreMenu.stories.js

This PR will add a `more_vert` icon for a list of individual row actions we can add for single operations like edit, delete, restart, snapshot, etc.

ListTable Row actions

---

src/app/core/common/EnhancedTableHead.js
src/app/core/common/ListTableSelect.js
src/app/plugins/openstack/components/images/ImageChooser.js
src/app/plugins/openstack/components/images/actions.js
src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/app/plugins/openstack/components/volumes/VolumeChooser.js
src/app/plugins/openstack/components/volumes/VolumeSnapshotsList.js
src/stories/common/ListTable.stories.js
src/stories/common/ListTableSelect.stories.js

I created a `<ListTableSelect>` component to allow us to have a picker in the form of a table.
Next step is to integrate it into the `AddVolumeForm`.

Create volumes from existing sources

---

src/app/core/common/ListTable.js
src/app/plugins/kubernetes/components/apiAccess/ApiAccessPage.js
src/app/plugins/kubernetes/components/apps/AppsIndexPage.js
src/app/plugins/kubernetes/components/infrastructure/CloudProvidersListPage.js
src/app/plugins/kubernetes/components/infrastructure/ClustersList.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListContainer.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/InfrastructurePage.js
src/app/plugins/kubernetes/components/infrastructure/NodesListPage.js
src/app/plugins/kubernetes/components/infrastructure/actions.js
src/app/plugins/kubernetes/components/namespaces/NamespacesPage.js
src/app/plugins/kubernetes/components/pods/PodsIndexPage.js
src/app/plugins/kubernetes/components/storage/StorageClassesPage.js
src/app/plugins/kubernetes/components/userManagement/UserManagementIndexPage.js
src/app/plugins/kubernetes/index.js

This doesn't have a lot of functionality but it sets up a lot of the scaffolding for K8s.

K8s scaffolding pages

---

package-lock.json
package.json
src/app/core/common/InfoTooltip.js
src/app/core/common/validated_form/Checkbox.js
src/app/core/common/validated_form/KeyValuesField.js
src/app/core/common/validated_form/TenantRolesContainer.js
src/app/core/common/validated_form/TextField.js
src/app/core/common/validated_form/ValidatedForm.js
src/app/core/common/validated_form/withFormContext.js
src/server/middleware.js
src/stories/common/ValidatedForm.stories.js

Created info tooltip that correctly positions relative to the input. Just a wrapper of material-ui Tooltip.
I had to update material-ui libraries as it had some issues with the tooltip.

Info tooltip

---

src/app/core/common/list_table/ListTable.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/actions.js
src/app/utils/__tests__/misc.test.js
src/app/utils/misc.js

This adds some more fields to the clusters list view.
Usage stats are not correct for some reason.  I'm not sure why the totals don't match the old UI.  Still investigating that part.

More cluster list columns

---

src/api-client/Keystone.js
src/app/plugins/openstack/components/SessionManager.js
src/app/plugins/openstack/components/tenants/TenantChooser.js
src/app/plugins/openstack/components/tenants/actions.js

This isn't future-proof yet -- I foresee some issues to come when editing the logged-in user's tenant privileges.

Updated user projects API call to use keystone auth endpoint

---

src/app/core/common/HotKeysProvider.js
src/app/core/common/list_table/ListTable.js
src/app/core/common/list_table/ListTableColumnPopover.js
src/app/core/common/list_table/ListTableFiltersButton.js
src/app/core/common/list_table/ListTableFiltersPopover.js
src/app/core/common/list_table/ListTableHead.js
src/app/core/common/list_table/ListTableToolbar.js
src/app/core/fp.js
src/app/utils/misc.js
src/stories/common/ListTable.stories.js

Table rows filtering

---

src/app/core/common/Navbar.js
src/app/core/common/Tabs.js
src/app/core/fp.js
src/app/core/pluginManager.js
src/app/theme.js
src/stories/common/Navbar.stories.js
src/stories/common/fakeNavbarItem.js

Navbar improvements and fixes for #219

---

src/app/plugins/kubernetes/index.js

This is currently a WIP and is current blocked by some issues (https://github.com/platform9/pf9-ui-plugin/issues/219).

Add Navbar nestedLinks for the Kubernetes plugin

---

src/app/core/common/HotKeysProvider.js
src/app/core/common/Navbar.js

Missing: keep section expanded after navigating to a sublink, improve styling

Improve nav menu filtering and allow navigating using keyboard (arrows and enter keys)

---

src/api-client/ResMgr.js
src/app/core/DataLoader.js
src/app/core/common/InfoPanel.js
src/app/core/common/ProgressBar.js
src/app/core/common/SimpleLink.js
src/app/core/common/Tabs.js
src/app/core/fp.js
src/app/plugins/kubernetes/components/infrastructure/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/ClusterInfo.js
src/app/plugins/kubernetes/components/infrastructure/ClusterNodes.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/NodesListPage.js
src/app/plugins/kubernetes/components/infrastructure/UpdateCloudProviderPage.js
src/app/plugins/kubernetes/components/infrastructure/actions.js
src/app/plugins/kubernetes/index.js
src/app/utils/misc.js
src/stories/common/InfoPanel.stories.js

Issue: #222 
I added an `<InfoPanel>` component that we can reuse elsewhere.
I also noticed the renderProp pattern was getting a bit messy with `<DataLoader`> and requiring more `import`s than I wanted.  I created a `withDataLoader` helper that cleans up the code a bit.

Cluster details page

---

src/app/core/common/dashboard_graphs/UsageBar.js
src/app/core/common/dashboard_graphs/UsageWidget.js
src/app/plugins/kubernetes/components/infrastructure/ClusterInfo.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusterUsageStats.js
src/stories/charts/UsageBar.stories.js
src/stories/charts/UsageWidget.stories.js

Add cluster resource widgets to cluster details and clusters list

---

src/app/core/common/list_table/ListTable.js
src/app/core/common/list_table/ListTableHead.js
src/app/core/common/list_table/ListTableRowActions.js
src/app/core/common/list_table/ListTableToolbar.js
src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js

This is a first attempt at incorporating "row actions" for `<ListTable>`s.  I'm looking for feedback on this approach.
Some context:
* Row actions are actions that can be performed by selecting one or more rows in a table.
* Row actions may or may not be possible depending on the selected rows.
Still to do:
* If an action is not allowed, provide a mechanism to show a Tooltip explaining why.

Implement table functionality for row actions

---

src/server/api/qbert/index.js
src/server/api/qbert/storageClasses/storageClassActions.js
src/server/context/simulator.js
src/server/models/qbert/StorageClass.js
src/server/models/qbert/__tests__/StorageClass.js
src/server/presets/dev.js

Implemented storage classes in simulator

---

src/app/App.js
src/app/core/common/ToastProvider.js
src/stories/common/Toast.stories.js
src/stories/helpers.js

Added component to display messages on a diversity of events or notifications

---

src/app/core/components/validatedForm/CodeMirror.js
src/app/core/components/validatedForm/PicklistField.js
src/app/core/components/validatedForm/withFormContext.js
src/app/plugins/kubernetes/components/pods/AddPodPage.js

Had some difficulties adding form validation to PickListField, I was able to get it working by adding the validations prop to the withFormContext component, but I'm not sure if that was the right thing to do or not.

start of form validation for pods page

---

package-lock.json
package.json
src/app/core/components/AppContainer.js
src/app/plugins/hackathon/components/Demo.js
src/app/plugins/hackathon/components/Draggable.js
src/app/plugins/hackathon/components/Grid.js
src/app/plugins/hackathon/components/Hotkeys.js
src/app/plugins/hackathon/components/NodeEditor.js
src/app/plugins/hackathon/components/PropertyInspector.js
src/app/plugins/hackathon/components/SVGCanvas.js
src/app/plugins/hackathon/components/ToolButton.js
src/app/plugins/hackathon/components/ToolPalette.js
src/app/plugins/hackathon/components/panels/ActivityPropertyPanel.js
src/app/plugins/hackathon/components/panels/CommonPanel.js
src/app/plugins/hackathon/components/panels/StartPropertyPanel.js
src/app/plugins/hackathon/components/symbols/ActivitySymbol.js
src/app/plugins/hackathon/components/symbols/StartSymbol.js
src/app/plugins/hackathon/components/utils/calcWireCoords.js

Node editor functionality includes:
* Draggable nodes
* Canvas area with panning and zooming
* Start node
* Activity node
* Add nodes from palette
* Property inspector
* Wire nodes together

Draggable nodes, start node, activity node, misc refinements

---

src/app/constants.js
src/app/core/components/Toolbar.js
src/app/plugins/openstack/components/SessionManager.js
src/app/plugins/openstack/components/regions/RegionChooser.js

This implements the long overdue `RegionChooser`.
I also did some refactoring.  Most notable is the introduction of a new `constants.js` file so we don't have hard-coded paths and strings scattered throughout the codebase.

RegionChooser

---

src/app/app.css
src/app/core/components/Navbar.js

First pass to just get the look similar. Still need to fully understand material UI styling, so will be investigating the proper way to utilize theme etc.

Navbar look to match old UI

---

.travis.yml
src/app/constants.js
src/app/core/components/Navbar.js
src/app/core/components/Selector.js
src/app/core/components/Toolbar.js
src/app/core/components/UserMenu.js
src/app/plugins/kubernetes/index.js
src/app/plugins/openstack/components/regions/RegionChooser.js
src/app/plugins/openstack/components/tenants/TenantChooser.js
src/app/static/index.html

Add nav icons.  Styling changes for sideNav and topNav

---

src/app/App.js
src/app/core/DataLoader.js
src/app/core/components/AutocompleteBase.js
src/app/core/components/InfoTooltip.js
src/app/core/components/Picklist.js
src/app/core/components/ProgressBar.js
src/app/core/components/Wizard.js
src/app/core/components/dashboardGraphs/SemiCircle.js
src/app/core/components/validatedForm/CheckboxField.js
src/app/core/components/validatedForm/PicklistField.js
src/app/core/components/validatedForm/TextField.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/helpers/createFormComponent.js
src/app/plugins/kubernetes/components/infrastructure/AddClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/ClusterInfo.js
src/app/plugins/kubernetes/components/infrastructure/ClusterScaleDialog.js
src/app/plugins/openstack/components/images/AddImagePage.js
src/app/plugins/openstack/components/images/UpdateImageForm.js
src/app/plugins/openstack/components/networks/AddNetworkPage.js
src/app/plugins/openstack/components/networks/UpdateNetworkPage.js
src/app/plugins/openstack/components/routers/AddRouterPage.js
src/app/plugins/openstack/components/routers/UpdateRouterPage.js
src/app/plugins/openstack/components/volumes/AddVolumeForm.js
src/app/plugins/openstack/components/volumes/UpdateVolumeForm.js
src/app/theme.js
src/stories/common/ValidatedForm.stories.js
src/stories/helpers.js

Form styles adjustments, migration to ThemeProvider (from MuiThemeProvider) and misc style fixes

---

package-lock.json
package.json
src/app/App.js
src/app/ThemeManager.js
src/app/core/components/Navbar.js
src/app/plugins/index.js
src/app/plugins/theme/components/ColorPicker.js
src/app/plugins/theme/components/ColorsPanel.js
src/app/plugins/theme/components/ConfigureThemePage.js
src/app/plugins/theme/components/KitchenSink.js
src/app/plugins/theme/components/MiscPanel.js
src/app/plugins/theme/components/Panel.js
src/app/plugins/theme/components/TypographyPanel.js
src/app/plugins/theme/components/TypographyVariant.js
src/app/plugins/theme/components/examples/ButtonsExample.js
src/app/plugins/theme/components/examples/FormExample.js
src/app/plugins/theme/components/examples/TablesExample.js
src/app/plugins/theme/components/examples/TabsExample.js
src/app/plugins/theme/components/examples/TypographyExample.js
src/app/plugins/theme/components/examples/WizardExample.js
src/app/plugins/theme/index.js

* Created a plugin to allow customization of the theme values.
* Added color picker component.
* Added a `<KitchenSink />` component where we can add our component library.
* Added common palette colors in property inspector area.
Future Work:
* Add more components to `<KitchenSink />` preview
* Load theme
* Save theme

Start of work on theming support

---

config.example.js
src/api-client/Keystone.js
src/app/App.js
src/app/plugins/openstack/components/SessionManager.js
src/app/plugins/openstack/components/regions/RegionChooser.js

Basically removed the part that set the active region in App.js from config, and instead set the active region during Session setup.

Fixed issue with API client using wrong region

---

src/app/ThemeManager.js
src/app/core/components/SearchBar.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/listTable/ListTableColumnSelector.js
src/app/core/components/listTable/ListTableFilters.js
src/app/core/components/listTable/ListTableFiltersButton.js
src/app/core/components/listTable/ListTableHead.js
src/app/core/components/listTable/ListTableRowActions.js
src/app/core/components/listTable/ListTableToolbar.js
src/app/theme.js

Some styling changes to make tables look 
https://zpl.io/2GGkJR9
https://zpl.io/aBRkJdA
I also had to add a reference to the font awesome icons, as it turns out we didn't have them in the project.

Added font-awesome icons and ListTable component styling changes

---

src/api-client/Qbert.js
src/app/plugins/kubernetes/components/prometheus/PrometheusAlertManagers.js
src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
src/app/plugins/kubernetes/components/prometheus/PrometheusRules.js
src/app/plugins/kubernetes/components/prometheus/PrometheusServiceMonitors.js
src/app/plugins/kubernetes/components/prometheus/UpdatePrometheusAlertManagerPage.js
src/app/plugins/kubernetes/components/prometheus/actions.js
src/app/plugins/kubernetes/index.js

This exposes the ability to edit Prometheus Alert Managers.

Update Prometheus Alert Manager

---

src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js

When creating a Prometheus instance there is a picklist that allows the user to pick from a list of clusters.
This PR makes it only show the clusters that have Prometheus enabled on them.

Filter out clusters w/o monitoring support

---

src/app/core/components/Navbar.js
src/app/core/components/Toolbar.js
src/app/core/components/TopExtraContent.js
src/app/core/helpers/createCRUDComponents.js
src/app/plugins/kubernetes/components/namespaces/NamespacesListPage.js
src/app/plugins/kubernetes/components/pods/DeploymentsListPage.js
src/app/plugins/kubernetes/components/pods/PodsListPage.js
src/app/plugins/kubernetes/components/pods/ServicesListPage.js
src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
src/app/plugins/openstack/components/flavors/FlavorsListPage.js
src/app/plugins/openstack/components/floatingips/FloatingIpsListPage.js
src/app/plugins/openstack/components/networks/NetworksListPage.js
src/app/plugins/openstack/components/routers/RoutersListPage.js
src/app/plugins/openstack/components/sshkeys/SshKeysListPage.js
src/app/plugins/openstack/components/tenants/TenantsListPage.js

Top extra content using a React Portal

---

src/api-client/Qbert.js
src/app/core/DataLoader.js
src/app/core/components/cardTable/CardTableToolbar.js
src/app/core/helpers/contextLoader.js
src/app/core/helpers/createCRUDComponents.js
src/app/core/hocs/withDataLoader.js
src/app/core/hocs/withDataMapper.js
src/app/core/hocs/withParams.js
src/app/core/providers/PreferencesProvider.js
src/app/plugins/kubernetes/components/apps/AppCatalogPage.js
src/app/plugins/kubernetes/components/apps/DeployedAppsListPage.js
src/app/plugins/kubernetes/components/apps/RepositoriesListPage.js
src/app/plugins/kubernetes/components/infrastructure/AddClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/ClusterAttachNodeDialog.js
src/app/plugins/kubernetes/components/infrastructure/ClusterDetachNodeDialog.js
src/app/plugins/kubernetes/components/infrastructure/ClusterInfo.js
src/app/plugins/kubernetes/components/infrastructure/ClusterNodes.js
src/app/plugins/kubernetes/components/infrastructure/ClusterScaleDialog.js
src/app/plugins/kubernetes/components/infrastructure/NodesChooser.js
src/app/plugins/kubernetes/components/namespaces/NamespacesListPage.js
src/app/plugins/kubernetes/components/pods/AddDeploymentPage.js
src/app/plugins/kubernetes/components/pods/AddPodPage.js
src/app/plugins/kubernetes/components/pods/AddServicePage.js
src/app/plugins/kubernetes/components/pods/DeploymentsListPage.js
src/app/plugins/kubernetes/components/pods/PodsListPage.js
src/app/plugins/kubernetes/components/pods/ServicesListPage.js
src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
src/app/plugins/kubernetes/helpers/clusterizedDataLoader.js
src/app/plugins/openstack/components/regions/RegionChooser.js

As discussed with Brennan, this is part of the work for decoupling the data loading logic into smaller functions and HoC's
The implementation in the views looks as follows (complex example):
Currently still fixing a few issues and preparing some tests.

Creating composable HoCs for data loading and mapping

---

src/api-client/Qbert.js
src/app/plugins/kubernetes/components/storage/StorageClassesPage.js
src/app/plugins/kubernetes/components/storage/actions.js

This just lists Storage Classes.  Other CRUD actions will be done in a different PR.

List storage classes

---

src/app/plugins/kubernetes/components/storage/StorageClassesPage.js
src/app/plugins/kubernetes/components/storage/actions.js

This adds the ability to delete storage classes.

Delete storage class

---

src/app/core/components/AppContainer.js
src/app/core/components/Navbar.js

Collapse left nav bar to icons instead of gone completely

---

src/app/ThemeManager.js
src/app/constants.js
src/app/core/components/AppContainer.js
src/app/core/components/KeyValues.js
src/app/core/components/Navbar.js
src/app/core/components/Toolbar.js
src/app/core/components/validatedForm/CheckboxField.js
src/app/core/components/validatedForm/PicklistField.js
src/app/core/components/validatedForm/TextField.js
src/app/core/helpers/contextLoader.js
src/app/core/helpers/createFormComponent.js
src/app/plugins/kubernetes/components/infrastructure/KubeCLI.js
src/app/plugins/kubernetes/index.js
src/stories/common/Navbar.stories.js

* Fixed `Warning: Function components cannot be given refs.`
* Removed search bar
* Added Dashboard link
* Reduced NavBar width to 180px
* Misc styling adjustments to NavBar
* Showing top bar at full width
* Removing side-nav subitems
When NavBar expanded:
When NavBar minimized:

Remove search bar and other fixes

---

src/app/core/components/FontAwesomeIcon.js
src/app/core/components/FormWrapper.js
src/app/core/components/buttons/CloseButton.js
src/app/core/components/buttons/NextButton.js
src/app/plugins/theme/components/ConfigureThemePage.js

* Changed the back to list view button to a close button like the current UI.
* Fixed the arrow on the next button.

Small misc design tweaks

---

src/app/core/components/Toolbar.js
src/app/core/components/progress/Progress.js
src/app/core/components/validatedForm/PicklistField.js
src/app/core/helpers/clusterContextUpdater.js
src/app/core/helpers/contextUpdater.js
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/namespaces/actions.js
src/app/plugins/kubernetes/components/pods/actions.js
src/app/plugins/kubernetes/components/prometheus/actions.js
src/app/plugins/kubernetes/components/userManagement/TenantsListPage.js
src/app/plugins/kubernetes/components/userManagement/UserGroupsListPage.js
src/app/plugins/kubernetes/components/userManagement/UsersListPage.js
src/app/plugins/kubernetes/components/userManagement/actions.js
src/app/plugins/openstack/components/floatingips/actions.js
src/app/plugins/openstack/components/networks/actions.js
src/app/plugins/openstack/components/routers/actions.js
src/app/plugins/openstack/components/sshkeys/actions.js
src/app/plugins/openstack/components/tenants/actions.js
src/app/plugins/openstack/components/users/actions.js
src/server/api/keystone/getGroups.js
src/server/api/keystone/getMappings.js
src/server/api/keystone/getRoles.js
src/server/api/keystone/getTenantUsers.js
src/server/api/keystone/index.js
src/server/context/simulator.js
src/server/models/openstack/Group.js
src/server/models/openstack/Mapping.js
src/server/models/openstack/Role.js
src/server/models/openstack/TenantUser.js
src/server/presets/dev.js

* Added simulator models and routes for tenants, users, roles and groups
* Add missing ID (hidden) columns in Tenants & Users pages
* Fixed Progress component positioning
* Fix Picklist tooltip opening when focusing input (eg via keyboard)
* Remove shadow from Toolbar and Buttons
* Fix issue with clusterContextUpdater

Add missing simulator tenant & users models and other fixes

---

src/api-client/Qbert.js
src/app/constants.js
src/app/core/components/CRUDListContainer.js
src/app/core/components/MoreMenu.js
src/app/core/components/Toolbar.js
src/app/core/components/TopExtraContent.js
src/app/core/components/cardTable/CardTable.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/components/validatedForm/withFormContext.js
src/app/core/components/wizard/Wizard.js
src/app/core/helpers/createCRUDComponents.js
src/app/core/helpers/createContextLoader.js
src/app/core/helpers/createContextUpdater.js
src/app/core/hooks/useDataLoader.js
src/app/core/hooks/useDataUpdater.js
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/apps/AddRepoDialog.js
src/app/plugins/kubernetes/components/apps/AppCard.js
src/app/plugins/kubernetes/components/apps/EditRepoClustersDialog.js
src/app/plugins/kubernetes/components/apps/RepositoriesListPage.js
src/app/plugins/kubernetes/components/apps/actions.js
src/app/plugins/kubernetes/components/infrastructure/actions.js
src/app/plugins/kubernetes/components/prometheus/actions.js
src/app/utils/fp.js

* Fix form validations when combined with `Wizard` component
* Prevent moving to next `Wizard` step if form has errors
* Fix issue with bulk deleting when using `useDataUpdater` hook
* Fix issue with right-top extra content not rendering Portal contents in some cases (when refreshing page)
* Implement Edit repo clusters functionality
* Implement Add repository functionality
* Implement Delete repository functionality
* Reduced table paddings and some font sizes to match the Clarity UI
* Misc minor fixes and refactoring related to error handling and sorting

Wizard & Form fixes, Repository actions, and others

---

package-lock.json
package.json
src/app/core/components/MultiSelect.js
src/app/plugins/kubernetes/components/infrastructure/NodesChooser.js
src/stories/common/MultiSelect.stories.js
src/stories/config.js

Our current `MultiSelect` didn't match our old UI `MultiSelect` component at all. So I'm rebuilding it to work and look like the previous one, and possibly add new desired features described in the `PMK Feature Parity Checklist` document.
TODO:
- Work on the visuals
- Fixed height for the component?
- Option styles
- Search input styles
Storybook Screenshot

[WIP] MultiSelect Component

---

src/app/plugins/kubernetes/components/logging/LoggingPage.js
src/app/plugins/kubernetes/index.js

This PR Adds a new Menu Item for Kubernetes plugin:
- Logging (beta)

Add Logging (beta) to Kubernetes Menu

---

src/app/core/components/listTable/ListTableBatchActions.js
src/app/core/components/listTable/ListTableToolbar.js
src/app/plugins/kubernetes/components/logging/LoggingPage.js

This PR uses stubbed data (no fetching for now), and implements:
- Table to display logging data
- Columns rendered according to the designs
- Batch action buttons according to the designs

Logging table

---

src/app/plugins/kubernetes/components/infrastructure/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/AwsClusterSshKeyPicklist.js
src/app/plugins/kubernetes/components/infrastructure/ClusterDomainPicklist.js
src/server/api/qbert/cloudProviders/getCpDetails.js

Adding more fields to the AWS cluster create wizard.

More AWS cluster create fields

---

src/app/core/components/RightAlign.js
src/app/core/components/expansionPanel/ExpansionPanel.js
src/app/plugins/kubernetes/components/dashboard/ClusterSetupWizard.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/index.js

First pass at guided welcome wizard, looking for feedback. Current placeholder data makes it look like below:

Started guided welcome wizard

---

src/app/core/components/AppContainer.js
src/app/static/index-with-tracking.html
src/app/static/index.html
src/app/utils/tracking.js
webpack.config.js

Page change tracking for Segment. Seemed to make sense to place into that component.
May be necessary to add a feature flag for this, like if we have e2e testing for example we don't want to be sending those events to Segment.

Added segment page tracking

---

src/app/plugins/kubernetes/components/infrastructure/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/AzureAvailabilityZoneChooser.js
src/app/plugins/kubernetes/components/infrastructure/AzureClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/AzureResourceGroupPicklist.js
src/app/plugins/kubernetes/components/infrastructure/AzureSkuPicklist.js
src/app/plugins/kubernetes/components/infrastructure/AzureSubnetPicklist.js
src/app/plugins/kubernetes/components/infrastructure/AzureVnetPicklist.js
src/app/plugins/kubernetes/index.js
src/server/api/qbert/cloudProviders/getCpDetails.js
src/server/presets/dev.js

The Azure Cluster Create is very similar to AWS.  I'm just copying it and will make the tweaks in future commits.

Azure cluster creation

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/VipInterfaceChooser.js

* Make Virtual IP conditionally required when number of master nodes > 1
* Allow user to specify multiple Metal LB IP pool ranges
* Change network interface picklist to only use interface name (not IP)

Small tweaks to Bare OS Cluster creation

---

src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js

If there is already a default storage class for the chosen cluster, `isDefault` checkbox will be disabled.

Storage classes isDefault behaviour

---

src/api-client/Keystone.js
src/api-client/helpers.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/listTable/ListTableToolbar.js
src/app/core/components/listTable/PerPageControl.js
src/app/core/components/validatedForm/CheckboxField.js
src/app/core/components/validatedForm/CodeMirror.js
src/app/core/components/validatedForm/KeyValuesField.js
src/app/core/components/validatedForm/PicklistField.js
src/app/core/components/validatedForm/TextField.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/components/validatedForm/withFormContext.js
src/app/core/helpers/createContextLoader.js
src/app/plugins/kubernetes/components/userManagement/AddTenantPage.js
src/app/plugins/kubernetes/components/userManagement/RolesPicklist.js
src/app/plugins/kubernetes/components/userManagement/TenantsListPage.js
src/app/plugins/kubernetes/components/userManagement/UserRolesTableField.js
src/app/plugins/kubernetes/components/userManagement/actions.js
src/app/plugins/kubernetes/index.js
src/app/plugins/openstack/components/api-access/actions.js
src/app/plugins/openstack/components/users/AddUserPage.js
src/app/plugins/openstack/components/users/TenantRolesContainer.js
src/app/plugins/openstack/components/users/UpdateUserPage.js

... and ListTable performance improvements + added `Component` option in the columns definition to allow rendering a custom component inside of each cell.

Add Tenant page and delete Tenant action

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AwsAvailabilityZoneChooser.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterVpcPicklist.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AwsZoneVpcMappings.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/utils/__tests__/misc.test.js
src/app/utils/misc.js

There are numerous errors when trying to submit the POST call.  This fixes some of them.
There are a few more that are still needed.  I will remove the WIP once those are fixed as well.

Misc fixes for AWS cluster creation submit

---

src/api-client/Keystone.js
src/app/core/components/CRUDListContainer.js
src/app/core/components/FormWrapper.js
src/app/core/components/cardTable/CardTable.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/listTable/ListTableHead.js
src/app/core/components/progress/Progress.js
src/app/core/components/tabs/Tabs.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/apps/AddRepoDialog.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterScaleDialog.js
src/app/plugins/kubernetes/components/userManagement/tenants/AddTenantPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/EditTenantPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/TenantsListPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/UserRolesTableField.js
src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
src/app/plugins/kubernetes/components/userManagement/users/actions.js
src/app/plugins/kubernetes/index.js

* Styling adjustments
* Fix warning about "compact" prop
* Fix misc ListTable issues
* Edit Tenant feature

Misc fixes and edit Tenant dialog

---

package-lock.json
package.json
src/app/app.css
src/app/core/utils/colorHelpers.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/components/dashboard/status-card.tsx
src/app/plugins/kubernetes/components/pods/actions.js
src/app/static/images/dynamic_feed.svg
src/app/static/images/icon-cloud.svg
tsconfig.json
webpack.config.js

General purpose stats with a callout for failed / pending when applicable.
Each card links to the appropriate section for the user to see more details.

Updated the dashboard page to reflect some current overall stats

---

package-lock.json
package.json
src/api-client/Keystone.js
src/app/core/components/FormWrapper.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/components/validatedForm/withFormContext.js
src/app/core/helpers/createContextUpdater.js
src/app/core/themes/defaultTheme.js
src/app/core/utils/fieldValidators.js
src/app/plugins/kubernetes/components/common/ClusterPicklist.js
src/app/plugins/kubernetes/components/userManagement/common/RolesPicklist.js
src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
src/app/plugins/kubernetes/components/userManagement/users/AddUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/EditUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/TenantRolesTableField.js
src/app/plugins/kubernetes/components/userManagement/users/UsersListPage.js
src/app/plugins/kubernetes/components/userManagement/users/actions.js
src/app/plugins/kubernetes/index.js
webpack.config.js

Also fixes some issues and errors in ValidatedForm and validations
TODO: dev server api resources and action create/update functions

Add/Edit User pages (Tenants & Users section)

---

.babelrc
package-lock.json
package.json
src/app/core/components/FormWrapper.js
src/app/plugins/kubernetes/components/common/CloudProviderCard.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/components/dashboard/status-card.tsx
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderPage.js
tsconfig.json
webpack.config.js

- Sourcemaps
- Import alias's
- Fixed path/import resolution in babel
- Misc cleanup

Typescript + babel support.

---

src/app/core/helpers/createContextUpdater.js

Thanks @kevinylee1991 for spotting this issue

Duplicated cache items on update

---

src/app/core/components/listTable/ListTable.js
src/app/core/helpers/createCRUDComponents.js
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/DownloadDialog.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js

This PR implements the UI for kubeconfig download dialog.

Kubeconfig Download Dialog UI

---

src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js

Removed the actions as well as multi-select functionality

Removed the edit actions as well as multi-select functionality.

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.js

Added support to display "Cloud Properties" depending on cluster type.

Added support to display "Cloud Properties" depending on cluster type.

---

src/api-client/Keystone.js
src/app/App.js
src/app/core/components/AppContainer.js
src/app/core/components/HostStatus.js
src/app/core/components/UserMenu.js
src/app/core/helpers/createContextLoader.js
src/app/plugins/index.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/openstack/components/LoginPage.js
src/app/plugins/openstack/components/LogoutPage.js
src/app/plugins/openstack/components/SessionManager.js
src/app/plugins/openstack/components/regions/RegionChooser.js
src/app/plugins/openstack/index.js

Also fixed some warnings and routing issues

Sending session cookie with keystone token using token2cookie endpoint

---

src/api-client/Qbert.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js

This address the following issues:
* [PMK-2165] AWS cluster create failing with "UUID undefined" error
* [PMK-2195] Cluster creation failed -- UI error not useful & bad input to backend/bad backend logic
* [PMK-2197] No feedback after clicking "create cluster" on last step of cluster creation wizard
* [PMK-2198] Cluster create completely broken for AWS if bad credentials
The following changes were made:
* Gives the user an indication after clicking the submit button that something is happening.
* Fix submit request body to support AWS Cluster auto-scaling.
* Perform additional GET call after cluster create to get the additional fields
[PMK-2165]: https://platform9.atlassian.net/browse/PMK-2165
[PMK-2195]: https://platform9.atlassian.net/browse/PMK-2195
[PMK-2197]: …

Misc AWS cluster create bugfixes

---

src/app/core/components/CodeBlock.tsx
src/app/core/components/ExternalLink.js
src/app/core/components/validatedForm/TextField.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js

Fixes:
https://platform9.atlassian.net/browse/PMK-2234
https://platform9.atlassian.net/browse/PMK-2235
https://platform9.atlassian.net/browse/PMK-2233

updates to tooltip messages

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterNodes.js

Added Refresh toolbar icon on Nodes list page in cluster detail page

Added Refresh toolbar icon on Nodes list page in cluster detail page

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderPage.js

Removed the VMware and OpenStack cloud provider from add cloud provider flow

PMK-2191:  Removed cloud provider creation for openstack and vmware

---

src/app/core/components/validatedForm/PicklistField.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
tsconfig.json

more tooltip updates

---

src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js

This PR gets the uses token as the authentication method to fill the kubeconfig token value.
Username/Password method will be implemented in another PR.

Save kubeconfig with token

---

src/app/core/components/tabs/Tabs.js
src/app/core/themes/defaultTheme.js

gray the tabs out more, fixes PMK-2194

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddAwsCloudProvider.js
src/app/plugins/kubernetes/components/userManagement/roles/actions.js

IAM Policy Link, User roles

---

src/app/core/components/wizard/Wizard.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js

Added a back option to each "Add Cluster" flow after selecting the platform. Fixes PMK-2213

Back to origin from the first Wizard step

---

src/app/plugins/kubernetes/components/apiAccess/kubeConfig/DownloadDialog.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js

This PR implements username/password auth method for downloading a kubeconfig.

Implement username/password auth method

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/VipInterfaceChooser.js

Handled the error case if master nodes not selected

PMK-2157: Handled the error case if master nodes not selected

---

package-lock.json
package.json
src/app/plugins/kubernetes/components/infrastructure/nodes/NodeDetailsPage.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js
src/app/plugins/kubernetes/components/infrastructure/nodes/model.ts
src/app/plugins/kubernetes/index.js
tsconfig.json

node detail page, fixes PMK-2265

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterSync.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js

added a spinning icon to represent transition states for a cluster

---

src/server/api/qbert/index.js

This PR fixes `npm run server`, that is currently broken.

Fix Server

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.js
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js

Hide the spot instance node column and spot instance fields for a cluster

PMK-2261: Hide the spot instance node column and spot instance fields for a cluster

---

src/app/core/helpers/createCRUDComponents.js
src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
src/app/plugins/kubernetes/components/userManagement/users/UsersListPage.js
src/app/plugins/kubernetes/components/userManagement/users/actions.js

Also fixed the showing of loading spinner when deleting an item in a List created using `createCRUDComponents` helper
Also fixes PMK-2160 (delete user)

[PMK 2244] Fix cache updating after create/update operations on users/tenants

---

src/app/core/utils/fieldValidators.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleWorkersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
webpack.config.js

This PR provides functionality for scaling the worker nodes on AWS and Azure clusters.

Scale cluster worker nodes for AWS and Azure

---

package-lock.json
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js

This makes it so users can't scale a cluster when it is in an `error` state or `converging`.

Only allow cluster scaling from valid state

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/model.ts
yarn.lock

The `ICluster` interface was autogenerated from [Paste JSON as Code](https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype) VS Code extension.
I modified it in a few spots where I knew it the data schema but some of it might still be a little off.  We can change it in the future as we notice the discrepancies or if we want to restrict it down further in the case of some of the enum string values.

Typescript support for cluster model

---

src/app/core/components/cardTable/CardTable.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.js

PMK-2323: Added Azure cloud property support, edit cloud provider for azure and misc changes like making secrete of type password.

PMK-2323: Added Azure cloud property support, edit cloud provider for azure and misc changes like making secrete of type password.

---

src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js

This update makes monitoring API calls async. Also, updates the cached cluster tags so that immediately clicking on it again shows the right control (enable->disable, disable->enable)

Make monitoring enable/disable async

---

src/app/core/containers/AppContainer.js

Identify the user in segment when segment is present

Identify user in Segment upon initializing UI

---

src/api-client/ApiClient.js
src/app/constants.js
src/app/core/components/notificationsPopover/NotificationItem.tsx
src/app/core/components/notificationsPopover/NotificationsPopover.tsx
src/app/core/hooks/useDataLoader.js
src/app/core/hooks/useDataUpdater.js
src/app/core/providers/AppProvider.tsx
src/app/plugins/kubernetes/components/userManagement/UserManagementIndexPage.js
src/app/plugins/kubernetes/components/userManagement/roles/actions.js
src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
src/app/plugins/kubernetes/components/userManagement/users/EditUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/UserPasswordField.js
src/app/plugins/kubernetes/components/userManagement/users/actions.js
src/app/plugins/openstack/components/regions/RegionChooser.js

* Branched off from https://github.com/platform9/pf9-ui-plugin/pull/530
* Fixed roles assignment when adding/editing Users & Tenants
* Fix patch request headers (fixes edit forms)
* Fix performance issue due to "registerNotification" being instantiated multiple times upon renders
* Fix minor styling issues
* Removed Groups tab to match the Clarity UI
* Fix region being written in user preferences twice

[PMK-2333] Fix user & tenants roles assignment

---

src/app/constants.js
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js

Change Qbert API doc link to the doc website instead of the version hosted on the DU.

PMK-2351 change Qbert doc link to doc website

---

src/app/constants.js
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
src/app/plugins/kubernetes/components/infrastructure/nodes/DownloadCliWalkthrough.tsx

added link for bareos explanation

---

src/app/core/components/MoreMenu.js
src/app/core/components/MultiSelect.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/tabs/Tabs.js
src/app/core/themes/defaultTheme.js
src/app/plugins/developer/components/ContextViewer.js
src/app/plugins/developer/components/DeveloperToolsEmbed.js
src/app/plugins/kubernetes/components/apps/AppDetailsPage.js
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx
src/app/plugins/kubernetes/components/namespaces/AddNamespacePage.js
src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
src/app/plugins/kubernetes/components/userManagement/roles/actions.js
src/app/plugins/openstack/components/hosts/HostsListPage.js
src/app/plugins/openstack/util/requiresAuthentication.js
src/app/plugins/theme/components/KitchenSink.js
src/app/plugins/theme/components/TypographyPanel.js
src/app/plugins/theme/components/TypographyVariant.js
src/app/static/images/dynamic_feed.svg
src/app/utils/misc.js

* Eliminate trailing dots in sanitized url's (https://platform9.atlassian.net/browse/PMK-2367)
* Fix role descriptions (https://platform9.atlassian.net/browse/PMK-2358)
* Fix MultiSelect uncaught error when `values` prop is not provided (https://platform9.atlassian.net/browse/PMK-2359)
* Fix regression with dev tools not working
* Adjust some colors to match new gray theming:

[PMK-2367 + PMK-2358 + PMK-2359] Remove trailing dots in domain names and misc fixes

---

src/app/core/hooks/useDataLoader.js
src/app/core/utils/fieldValidators.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.js
src/app/plugins/kubernetes/components/userManagement/users/UserPasswordField.js

Also added + character to the list of allowed special characters for password validation.
Moreover, I slightly improved the performance of components that used `useDataLoader` hook, by using `useReducer` instead of 2 `setState` and therefore preventing an unnecessary re-render every time data was being loaded.

[PMK-2373, 2374, 2376] Fix Clusters editing and filter out local Cloud Providers

---

src/app/core/components/SearchBar.js
src/app/core/components/buttons/NextButton.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/listTable/ListTableHead.js
src/app/core/components/progress/ProgressBar.js
src/app/core/components/tabs/Tabs.js
src/app/core/components/validatedForm/TextField.js
src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/components/wizard/Wizard.js
src/app/core/containers/AuthenticatedContainer.js
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx
src/app/static/images/dynamic_feed.svg

Changed the primary and secondary back to their original values.  Really just the top nav was meant to be grey.
Quantized font size values so they are closer.  Having 12px, 13px, 14px, 15px, and 16px all on the same page was really bad.
Tweaked, dashboard colors slightly and added a subtle drop shadow.
Tweaked form look and and feel.

Style tweaks

---

src/app/core/components/wizard/Wizard.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderPage.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/PromptToAddProvider.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/model.ts

Fixes PMK-2348
added logic for linking to creating a cloud provider when there are none of that type
deep linking to select the correct provider on first mount

Prompt to create cloud provider when none of type exist

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareOsClusterReviewTable.js

show selected nodes in the review table

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusSpan.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js

This PR fixes some health and connection status, based on discussion with Madhura.

[WIP] Bugfix/cluster status fixes

---

.eslintrc
src/api-client/ApiClient.js
src/api-client/ApiService.ts
src/api-client/Appbert.ts
src/api-client/Cinder.ts
src/api-client/Glance.ts
src/api-client/Keystone.ts
src/api-client/Murano.ts
src/api-client/Neutron.ts
src/api-client/Nova.ts
src/api-client/Qbert.ts
src/api-client/ResMgr.ts
src/app/bootstrap.js
src/app/core/containers/AppContainer.js
src/app/core/providers/AppProvider.tsx
src/app/core/public/LoginPage.js

Also converted remaining Api Services to Typescript

[PMK-2326] Logout user on session expiration

---

src/app/core/hooks/useDataLoader.js

This modifies the `useDataLoader` hook to monitor changes in its current loader cache array, so when the cache its updated it will automatically reload without the need of manually refreshing the data using the `reload` method provided by the hook.

Monitor cache changes

---

src/app/core/components/buttons/CardButton.js
src/app/core/containers/AuthenticatedContainer.js
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx

Old vs new. Madhura noted that it needs more color, but that this is a good starting point to check in. Icons need to be updated according to spec, but plan to do that in a different PR.

[PMK-2060] New dashboard styling

---

src/app/constants.js
src/app/core/components/HelpContainer.js
src/app/core/components/Toolbar.js
src/app/core/containers/AuthenticatedContainer.js
src/app/plugins/kubernetes/components/common/HelpPage.js

PMK-2305: Added help page.

---

src/app/core/helpers/createListTableComponent.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterNodes.js
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js

This PR implements Master Nodes and Worker Nodes tables.

Cluster nodes details page

---

src/app/core/components/Navbar.js

added titles to the sidebar icons so you know what the tab is when not expanded

---

src/app/core/components/Navbar.js

updated header in the sidebar to be what madhura wants

---

package.json
webpack.config.js
yarn.lock

- from 40s -> 70s
- to approx 7s -> 9s.

pull in hard-source-webpack-plugin to start caching the builds

---

src/app/core/public/ResetPasswordPage.js

Minor change. PMK-2426: Corrected the display message.

PMK-2426: Correct the display message.

---

src/app/core/components/listTable/ListTable.js
src/app/core/helpers/createCRUDComponents.js
src/app/plugins/kubernetes/components/apiAccess/ApiAccessListPage.js
src/app/plugins/kubernetes/components/apiAccess/ApiAccessPage.js
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js

JIRA Card: https://platform9.atlassian.net/browse/PMK-2405

Render table with empty text instead of text only

---

decco-container/Makefile

https://platform9.atlassian.net/browse/IAAS-10199

IAAS-10199: Cleanup docker image after push

---

src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js

PMK-2319 - Change isMaster column to Role

---

package.json
src/app/core/components/graphs/PieGraph.tsx
src/app/core/components/widgets/PieUsageWidget.tsx
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx

First pass at the pie chart -- still need to make some tweaks like adding it to the appropriate cards and support for more props. Need to talk to madhura about the appropriate statistics for each card.

Pie chart first pass

---

src/app/plugins/kubernetes/components/apiAccess/kubeConfig/DownloadDialog.js

This PR:
- Removes UI password validations (leaves the entire validation to the backend)
- Shows error message when the backend validation fails

PMK-2347 - Remove UI password validations from Kubeconfig download

---

src/app/core/components/graphs/PieGraph.tsx
src/app/core/components/widgets/PieUsageWidget.tsx
src/app/core/themes/defaultTheme.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.js
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx

Pie graph loader enhancements

---

src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/actions.js

updated wording, sort by cluster name, fixed caching issue off of uniqueIdentifier key

---

src/app/core/public/ActivateUserPage.tsx
src/app/core/utils/routes.ts
src/app/plugins/kubernetes/components/userManagement/users/AddUserPage.js

Tested manually on paavan's DU

[PMK-2442] Expose user creation with clemency and fix activation page reroute

---

src/app/core/providers/AppProvider.tsx

Refactored AppProvider from FC to a class. 
I know this will look strange, since we are refactoring most of our stuff to functional components, but in this specific case I have given up, since the problems and complexities of using hooks are too high and is simply much more optimal and easier to use a class component.
Additionally, `this.setState` has the advantage of allowing to pass a callback for when the state update operation has been performed, whereas doing the same with the `useState` hook is much more complicated (I had to create a `useStateAsync` hook which seems to be somewhat buggy)
This should also fix some weird issues related to cache updating.

[PMK-2532] Fix issues with app context updating/accessing

---

src/app/core/helpers/createContextUpdater.js
src/app/core/hooks/useDataUpdater.js

Added server response to the `onComplete` callback used by the `useDataUpdater` hook

Tweak oncomplete callback

---

src/app/plugins/kubernetes/components/infrastructure/nodes/DownloadCliPage.tsx

add a back link

---

src/app/core/public/ForgotPasswordPage.js
src/app/core/public/ResetPasswordPage.tsx

[PMK-2552] Fix password reset error alerts

---

src/app/core/containers/AppContainer.js
src/app/core/public/LoginPage.js
src/app/core/public/LogoutPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/utils/tracking.js
webpack.config.js

Bare-bones segment event implentation for a few metrics (logout, login, cluster creation). Still need to confirm with chris for fields that he wants to include. A UI-wide implementation will for sure need more discussion.

Added a few segment events for PMKFT GA

---

src/app/core/public/LogoutPage.js

Found a warning for this when i was compiling just now -- not sure how it got through tests the first time.

Fixed an import

---

src/app/constants.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js

Some parts of the UI expected tags to be a list of objects, while others expected it to be a dict. The dict is the correct format.

[PMK-2585] Fixed cluster tagging inconsistencies

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
src/app/plugins/kubernetes/components/infrastructure/clusters/TaskStatusDialog.js
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx

fixed the loading nodes issue, cleaned up the cluster status to do a bubble or icon not both, better styling

PMK-2567, PMK-2570. Cluster status and nodes

---

src/app/core/components/SimpleLink.tsx
src/app/core/components/validatedForm/PicklistField.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/ClusterHostChooser.tsx
yarn.lock

This should fix the issue with the Outlined labels in some components, eg: 
Before: 
Tried in Firefox and Chrome browsers

[PMK-2540] Update material-ui and fix some styling issues

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AwsRegionFlavorPicklist.js

Aws flavors

---

src/app/constants.js
src/app/core/components/listTable/ListTable.js
src/app/core/components/validatedForm/FormFieldCard.tsx
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/namespaces/AddNamespacePage.js
src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js

Design cleanup 

---

src/app/constants.js
src/app/core/components/expansionPanel/ExpansionPanel.js
src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js
src/app/plugins/kubernetes/components/common/HelpPage.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddAwsCloudProvider.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddAzureCloudProvider.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterAttachNodeDialog.js
src/app/plugins/kubernetes/components/infrastructure/clusters/azure/AzureClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareosClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/RemoteSupportDialog.js
src/app/plugins/kubernetes/components/onboarding/cluster-setup.tsx
src/app/plugins/kubernetes/components/onboarding/onboard-wizard.tsx
src/app/plugins/kubernetes/components/onboarding/pod-setup.tsx
src/app/plugins/kubernetes/components/pods/AddResourcePage.js
src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js
src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
src/app/plugins/kubernetes/links.ts

Updated: created a dedicated `links.js` file under the `kubernetes/` plugin folder and moved all the kubernetes related links to there.

[PMK-2557] Fix help page PMK documentation link

---

src/app/plugins/kubernetes/components/namespaces/NamespacesListPage.js
src/app/plugins/kubernetes/components/rbac/ClusterRoleBindingsListPage.js
src/app/plugins/kubernetes/components/rbac/ClusterRolesListPage.js
src/app/plugins/kubernetes/components/rbac/RoleBindingsListPage.js
src/app/plugins/kubernetes/components/rbac/RolesListPage.js
src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
src/app/plugins/kubernetes/components/storage/StorageClassesPage.js

PMK-2623: Added default cluster selection to 'All' in Storage, Namespace and RBC pages.
Added could provider filed in create storage class flow.

PMK-2623: Added default cluster selection to 'All' in Storage, Namespace and RBC pages.

---

src/app/plugins/kubernetes/components/infrastructure/clusters/aws/AwsClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/azure/AzureClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareosClusterRequirements.tsx
src/app/plugins/kubernetes/components/onboarding/OnboardWizard.tsx

PMK-2618: Changed the setup documentation link and description for AWS cluster creation.

PMK-2618: Changed the setup documentation link and description for AWS cluster creation.

---

src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx

updated cards to use css grid, mosaic layout for the landing page, put count below header as it feels more natural

PMK-2624, Dashboard page work

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddAwsCloudProvider.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddAzureCloudProvider.js
src/app/plugins/kubernetes/links.ts

updated cloud provider create forms, reduced text that was moved to documentation links and pointed at those.

PMK-2621, updated cloud provider create forms

---

src/app/plugins/kubernetes/components/pods/DeploymentsListPage.js
src/app/plugins/kubernetes/components/pods/PodsListPage.js
src/app/plugins/kubernetes/components/pods/ServicesListPage.js
src/app/plugins/kubernetes/components/pods/renderLabels.js

PMK-2622, consistency cleanup on these list pages

---

src/app/constants.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/links.ts

PMK-2604: Refactored the links and corrected some link

PMK-2604: Refactored the links and corrected some link

---

src/app/core/utils/__tests__/routes.test.ts
src/app/core/utils/routes.ts
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterNodes.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js

update node list page health status link to route (when applicable) to the health view. remove the disable next field on BareOS

PMK-2638, PMK-2608, status links, bug fix

---

src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js
src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/TaskStatusDialog.js
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/model.ts
src/app/plugins/kubernetes/links.ts

PMK-2641, show the kube state as a status when not ok, links for failed state

---

src/app/core/components/wizard/Wizard.js
src/app/core/components/wizard/WizardStep.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js

Wanted to attach chris to this PR so he could review the steps, but I'll just slack him instead

[PMK-2095] Pass step by step segment events for cluster creation wizards

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDeleteDialog.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.js
src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js
src/app/plugins/kubernetes/components/rbac/AddClusterRoleBindingPage.js
src/app/plugins/kubernetes/components/rbac/AddRoleBindingPage.js
src/app/plugins/kubernetes/components/rbac/RbacChecklist.tsx
src/app/plugins/kubernetes/components/rbac/UpdateClusterRoleBindingPage.js
src/app/plugins/kubernetes/components/rbac/UpdateClusterRolePage.js
src/app/plugins/kubernetes/components/rbac/UpdateRoleBindingPage.js
src/app/plugins/kubernetes/components/rbac/UpdateRolePage.js
src/app/plugins/kubernetes/components/userManagement/tenants/AddTenantPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/EditTenantPage.js
src/app/plugins/kubernetes/components/userManagement/users/AddUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/EditUserPage.js

added headers to a few form cards, fixed a few input widths,

Consistency updates in styling

---

src/app/core/components/listTable/ListTableBatchActions.js

[PMK-2667] Display table tool bar actions at all times

---

src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx

instead of filtering out the cards, we should just remove the permission to do certain actions on the card

PMK-2679 dashboard cards with conditional actions

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts

update cluster status messages to show a more detailed breakdown of counts when appropriate

PMK-2582, updates to cluster health status

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleWorkersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/TaskStatusDialog.js

Azure fixes

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/TaskStatusDialog.js
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx

Cluster health status again

---

src/app/plugins/kubernetes/components/userManagement/tenants/AddTenantPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/EditTenantPage.js
src/app/plugins/kubernetes/components/userManagement/users/AddUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/EditUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/TenantRolesTableField.js
src/app/plugins/kubernetes/components/userManagement/users/actions.js

Also fixed error messages when not selecting users/tenants

[PMK-2671] Revert selecting multiple tenants for every selected role

---

src/app/core/PushEventManager.tsx

This will fix "this" reference errors in some cases, eg:

Convert PushEventManager methods to arrow functions 

---

src/server/models/openstack/Catalog.js

Added mock endpoint for notifications ws to prevent UI error

Fix UI white screen on login when using simulator

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AzureClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareOsClusterReviewTable.js

Hide the application catalog from users and disable it for all cluster types

PMK-2720, Disable app catalog

---

.gitignore
README.md
build.bash
deploy.bash
support/Makefile

https://platform9.atlassian.net/browse/TESTS-1134

Auto deploy static content to target DUs after build

---

src/app/app.css
src/app/core/components/Navbar.js
src/app/core/components/graphs/SemiCircleGraph.js
src/app/core/components/listTable/ListTableToolbar.js
src/app/core/components/widgets/UsageWidget.js
src/app/core/components/widgets/WidgetCard.js

Few things to reflect the updated design
Usage widgets font color
___
Dropdown height now matches the search bar
___
smaller icons for sidebar

updates for the sidebar, dropdown padding in list table and font colors

---

src/app/core/PushEventManager.tsx
src/app/core/components/Picklist.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AzureClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/azure/AzureClusterRequirements.tsx

Less copy on the platform selection screen
___
always show enable workloads on masters
___
disable availability zone selection until region is specified
___
maximum height on picklists so long lists are usable especially on small screens

UX-18, UX-19, UX-16, UX-15 - updates to azure cluster create

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js

Fixes UX-54
Added segment tracking for azure cluster create, minor updates

segment tracking for azure

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleWorkersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/ClusterHostChooser.tsx

reworked the bareos initial flow to require node setup before doing anything else

UX-14, UX-94, UX-182, UX-135/BareOS Rework

---

src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js

keep the provisioner field on bareos when setting up a storage class

UX-152/bareos provisioner

---

src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js

update k8s dashboard url based on its version, fix an issue with storage classes throwing an exception

UX-196/update k8s dashboard url

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js

fixed a regression issue where the wrong value was being referenced

UX-199/reference the correct value

---

package.json
src/app/core/components/Navbar.js

add an app switcher to allow easy switching between applications, expose the app version

UX-189/App Switcher + Version

---

src/app/core/components/Navbar.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js

New required fields for calico
IP validation
Block size validation
fixed a bug where the screen would crash

UX-52, UX-126/Support for calico

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/PromptToAddProvider.tsx
src/app/utils/misc.js

[UX-142] Fixed text for cloud provider creation prompt

---

src/app/core/components/notifications/BannerContainer.tsx
src/app/core/containers/AuthenticatedContainer.js
src/app/plugins/kubernetes/index.js

add the sandbox banner into the new ui so users have a CTA while viewing the demo

UX-227/Sandbox Banner

---

src/app/core/components/MultiSelect.js
src/app/core/components/widgets/PieUsageWidget.tsx
src/app/core/utils/formatters.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AwsAvailabilityZoneChooser.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDeleteDialog.tsx

few misc fixes in formatting / styling / conditional messaging

UX-159, UX-167, UX-179/styling + formatting updates

---

src/app/plugins/kubernetes/components/infrastructure/common/ResourceUsageTable.js
src/app/plugins/kubernetes/components/pods/AddResourcePage.js

UX-151, UX-171/Bug cleanup

---

src/app/core/public/LoginPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareosClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/DownloadCliWalkthrough.tsx
src/app/plugins/kubernetes/links.ts

Wording updates
Hyperlink updates

UX-133, UX-247, UX-168, UX-175, UX-234, UX-162, UX-230/Misc updates to copy and links

---

src/app/plugins/kubernetes/components/userManagement/users/AddUserPage.js

UX-140/Require a valid email address when creating a user

---

src/app/core/components/validatedForm/ValidatedForm.js
src/app/core/public/ResetPasswordPage.tsx

Removing the css in ValidatedForm seemed to improve the look of the key/value form field as well
Old
New
Old
New

UX-137/Fixed reset password form styling

---

src/api-client/Keystone.ts
src/app/core/utils/fieldValidators.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleMastersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx
src/app/plugins/kubernetes/components/prometheus/actions.js

UX-268, UX-257, UX-195, UX-157, UX-147/Bug fixes

---

package.json
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
yarn.lock

UX-251/Validate azure ssh key

---

src/app/core/components/Picklist.js
src/app/plugins/kubernetes/components/userManagement/common/RolesPicklist.js
src/app/plugins/kubernetes/components/userManagement/tenants/EditTenantPage.js
src/app/plugins/kubernetes/components/userManagement/tenants/UserRolesTableField.js
src/app/plugins/kubernetes/components/userManagement/users/EditUserPage.js
src/app/plugins/kubernetes/components/userManagement/users/TenantRolesTableField.js

UX-281/Fix tenant/user picklist select background

---

src/app/core/components/DisplayKeyValues.tsx
src/app/plugins/kubernetes/components/alarms/AlarmDetailsDialog.tsx
src/app/plugins/kubernetes/components/alarms/AlarmDetailsLink.tsx
src/app/plugins/kubernetes/components/alarms/AlarmsListPage.tsx
src/app/plugins/kubernetes/components/alarms/model.ts

May need some help figuring out how to create the interface type for the render function in the DisplayKeyValues component

UX-286/Alarms details dialog

---

package.json
src/app/core/utils/__tests__/routes.test.ts
src/app/core/utils/routes.ts
src/app/utils/tracking.js
yarn.lock

This adds support for Segment Page events.
Additional functionality has been added to the `Route` object in `routes.ts` to support having a `name` and also for looking up a `Route` given a `location`.

UX-306 Segment page events

---

package.json
src/app/core/components/Navbar.js
src/app/plugins/developer/components/DeveloperToolsEmbed.js

Show the DU version in the sidebar
Show the App version in the developer tools

App Version

---

src/app/core/components/DisplayKeyValues.tsx
src/app/core/components/DisplayLabels.tsx
src/app/plugins/kubernetes/components/alarms/AlarmsListPage.tsx
src/app/plugins/kubernetes/components/alarms/actions.js
src/app/plugins/kubernetes/components/alarms/model.ts
src/app/plugins/kubernetes/components/monitoring/MonitoringPage.tsx
src/app/plugins/kubernetes/components/monitoring/RuleDetailsDialog.tsx
src/app/plugins/kubernetes/components/monitoring/RuleDetailsLink.tsx
src/app/plugins/kubernetes/components/monitoring/RulesListPage.tsx
src/app/plugins/kubernetes/index.js

Started moving resources into /kubernetes/monitoring

UX-288, UX-289/Rules list page and details dialog

---

src/app/plugins/kubernetes/components/namespaces/actions.js

Simple PR for adding Segment tracking events for `namespace` create and delete events.

UX-38 Segment namespace instrumentation

---

src/app/core/components/Navbar.js
src/app/core/containers/AuthenticatedContainer.js

Piyush's DU has an ironic / kubernetes region and apparently mavenir may have something similar, added the ability to switch between the two stacks.

UX-439/Add ability to switch between ironic and kubernetes stacks

---

src/app/plugins/kubernetes/components/common/HelpPage.js
src/app/plugins/kubernetes/links.ts
yarn.lock

UX-318/Removed email support from PMKFT UI

---

src/api-client/Qbert.ts
src/app/core/components/InfoPanel.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js

UX-96/Added CSI driver details to cluster overview

---

src/app/plugins/kubernetes/components/onboarding/ClusterSetup.tsx
src/app/plugins/kubernetes/links.ts

UX-136/Added link to kubectl docs

---

src/app/plugins/kubernetes/components/infrastructure/nodes/model.ts
src/app/plugins/kubernetes/components/onboarding/PodSetup.tsx
src/app/plugins/kubernetes/components/pods/models.tsx

[Screen Recording 2020-08-24 at 11.00.33 PM.zip](https://github.com/platform9/pf9-ui-plugin/files/5125269/Screen.Recording.2020-08-24.at.11.00.33.PM.zip)

UX-436/Fixed 'Create a sample pod' task completion problem

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/AddBareOsClusterPage.js

UX-416/Modified the conditions that allow the 'Finish and Review' button to be shown

---

src/app/plugins/kubernetes/components/pods/DeploymentsListPage.js
src/app/plugins/kubernetes/components/pods/PodsListPage.js

UX-519/Added delete option to pods list

---

src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js

Changes to a cluster's etcd backup properties are now reflected in the UI
[Edit Etcd Backup Interval.mov.zip](https://github.com/platform9/pf9-ui-plugin/files/5191881/Edit.Etcd.Backup.Interval.mov.zip)

UX-278/Fixed cluster etcd backup problem

---

src/app/core/components/listTable/ListTable.js
src/app/core/components/listTable/ListTableBatchActions.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/selectors.ts
src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js

Fixed ListTable to correctly update the selected rows when a row is updated, and other misc fixes

UX-574/Fix monitoring modal and other fixes

---

src/app/core/public/ResetPasswordPage.tsx

UX-186/Disabled email field in Password Reset form

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js

UX-521/Added cluster update time to cluster table and cluster details

---

src/api-client/Qbert.ts
src/api-client/qbert.model.ts
src/app/plugins/kubernetes/components/alarms/AlarmDetailsDialog.tsx
src/app/plugins/kubernetes/components/alarms/AlarmDetailsLink.tsx
src/app/plugins/kubernetes/components/alarms/AlarmsListPage.tsx
src/app/plugins/kubernetes/components/alarms/actions.js
src/app/plugins/kubernetes/components/alarms/model.ts
src/app/plugins/kubernetes/components/alarms/selectors.ts
src/app/plugins/kubernetes/components/pods/renderLabels.js
src/app/plugins/kubernetes/datakeys.model.ts

Minor styling update, exposing more relevant data.

UX-580/Using AlertManager API for alerts

---

src/app/plugins/kubernetes/components/alarms/TimePicklist.js
src/app/plugins/kubernetes/components/common/CloudProviderPicklist.js

Picklist default props were getting rewritten unintentionally

UX-585/Fixed picklist alignment

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js

UX-577/Nodes & clusters show resource usage even when offline

---

src/app/plugins/kubernetes/components/common/CloudProviderRegionPicklist.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js

UX-524/Displayed region using 'DisplayName' instead of 'RegionName' to be more user friendly

---

src/app/core/components/validatedForm/PicklistField.js

UX-172/Modified InfoToolTip in PickListField

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleMastersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleWorkersPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js

- Payload for scaling worker nodes has been modified

UX-275/Modified payload for scaling master and worker nodes

---

src/app/core/containers/AppContainer.tsx

For sandbox autologin, take token url parameter

WEB-6/Added sandbox autologin with token URL param

---

src/app/core/components/validatedForm/CodeMirror.js
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js

UX-598/Changed kubeconfig's code component from CodeBlock to CodeMirror

---

src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/AzureClusterReviewTable.js
src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.js

Added Auto Scaling option to the Azure cluster creation form

UX-45/Added auto scaling option for Azure clusters

---

src/app/core/components/ConfirmationDialog.tsx
src/app/core/components/ExportDataButton.js
src/app/core/components/ImportDataButton.js
src/app/core/components/SubmitButton.js
src/app/core/components/buttons/BannerButton.tsx
src/app/core/components/buttons/CancelButton.js
src/app/core/components/buttons/CardButton.js
src/app/core/components/buttons/CloseButton.js
src/app/core/components/buttons/CreateButton.js
src/app/core/components/buttons/NextButton.js
src/app/core/components/buttons/PrevButton.js
src/app/core/components/buttons/SubmitButton.js
src/app/core/components/wizard/WizardButtons.js
src/app/core/elements/button.tsx
src/app/core/elements/icon-button.tsx
src/app/core/elements/input.tsx
src/app/core/elements/text.tsx
src/app/core/public/LoginPage.tsx
src/app/core/themes/relianceLight.ts
src/app/plugins/kubernetes/components/userManagement/tenants/TenantsListPage.js
src/app/plugins/kubernetes/components/userManagement/users/UsersListPage.js

Generic button component.
Generic input element.

updated styling for input elements and buttons, fixed login page

---

package.json
src/app/core/components/DocumentMeta.tsx
src/app/core/containers/AuthenticatedContainer.tsx
src/app/plugins/kubernetes/components/common/ListPageHeader.tsx
src/app/plugins/kubernetes/components/infrastructure/InfrastructurePage.tsx
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/CloudProviderListHeader.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/AddClusterPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPageHeader.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPageHeader.tsx
yarn.lock

Generic document meta component to update the title of the page plus some extra functionality around body class and id manipulation
___
- ### Title Manipulation
```
<DocumentMeta title="Clusters" />
```
- ### Body class manipulation for forms with a gray background
```
<DocumentMeta title="Add Cluster" bodyClasses={['form-view']} />
```

Document Meta

---

src/app/core/components/Navbar.js
src/app/core/components/expansionPanel/ExpansionPanel.js
src/app/core/components/widgets/PieUsageWidget.tsx
src/app/core/elements/button.tsx
src/app/core/themes/model.ts
src/app/core/themes/relianceLight.ts
src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
src/app/plugins/kubernetes/components/dashboard/StatusCard.tsx
src/app/plugins/kubernetes/components/onboarding/ClusterSetup.tsx
src/app/plugins/kubernetes/components/onboarding/OnboardWizard.tsx
src/app/plugins/kubernetes/components/onboarding/PodSetup.tsx

UX-606/dashboard page styles

---

src/app/core/components/buttons/BannerButton.tsx
src/app/core/components/notifications/BannerContainer.tsx
src/app/plugins/kubernetes/components/alarms/selectors.ts

fixed banner styling, fixed a crashing bug when no alert rules were found

---

src/api-client/qbert.model.ts
src/app/core/components/wizard/WizardMeta.tsx
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
src/app/plugins/kubernetes/components/pods/renderLabels.js

UX-640/wizard meta component

---

src/api-client/Keystone.ts
src/app/plugins/kubernetes/components/apiAccess/kubeConfig/DownloadKubeConfigForm.js
src/app/plugins/kubernetes/components/infrastructure/clusters/kubeconfig.tsx

Missed the kubeconfig token renewal

Use saml2 auth endpoint for SSO users for kubeconfig download

---

src/app/core/components/Alert.js
src/app/core/components/CodeBlock.tsx
src/app/core/components/CopyToClipboard.tsx
src/app/core/components/InfoPanel.js
src/app/core/components/widgets/DonutWidget.tsx
src/app/core/components/widgets/PieUsageWidget.tsx
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderCredentialStep.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/AddClusterPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareosClusterRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/ConvergingNodeBreakdown.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/NodeDetailsPage.tsx
src/app/utils/misc.js

UX-597/Better rendering of the task error.

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-multi-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-single-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-multi-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-single-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/cluster-addon-manager.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/kubevirt-plugin-operator.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/network-plugin-operator.tsx

UX-678/Added support for luigi and kubevirt

---

src/app/plugins/kubernetes/components/rbac/AddRolePage.js
src/app/plugins/kubernetes/components/rbac/actions.js

UX-605, UX-694/fixed issue with rbac form not loading and styling / spacing

---

src/app/plugins/kubernetes/components/infrastructure/nodes/DownloadCliWalkthrough.tsx

UX-741/Modified text for step 2 of DownloadCliWalkthrough

---

src/app/core/components/DocumentMeta.tsx
src/app/core/containers/AppContainer.tsx
src/app/static/index-with-tracking.html
src/app/utils/tracking.js

Segment tracking is now added based off of the `analyticsOff` feature flag
If `analyticsOff` === false || `analyticsOff` === undefined, then Segment will be enabled

UX-578/Added Segment tracking based off of 'analyticsOff' feature flag

---

src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/custom.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/api-fqdn.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/services-fqdn.tsx

UX-748/Reference wizard context value on api and service fqdns to show updated values

---

src/app/constants.ts
src/app/core/elements/button.tsx
src/app/plugins/account/components/secondaryHeaders/MyAccountHeader.tsx
src/app/plugins/account/components/secondaryHeaders/UpgradeButton.tsx

UX-706/Added upgrade now button for freedom/growth tiers

---

src/app/core/containers/AppContainer.tsx

Problem: 
`updateSession` uses a callback with an empty array as a dependency so we were getting the old user preferences when logging back in
Also, `currentTenant` is the tenant ID. When finding the `currentTenant` in the list of tenants, we should be doing `propOr('id', currentTenant)`, not `propOr('name', currentTenant)`

UX-775/Fixed bug related to user's currentTenant when logging out and then logging in again

---

src/app/core/helpers/createListTableComponent.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterNodes.js

UX-614/Added remote support action to nodes table in cluster details page

---

src/app/plugins/kubernetes/components/infrastructure/clusters/constants.ts

UX-796/Removed 'sudo' from prep-node command

---

src/app/plugins/kubernetes/links.ts

Updated links:
- Need Help -> View tutorials 
- API Access -> Want to know more about Qbert? 
- API Access -> KubeConfig & Client Help

UX-785/Updated links to direct to new PF9 Docs

---

src/app/core/public/ResetPasswordPage.tsx

Fixed issue where password reset page wouldn't load

UX-798/Fix password reset page

---

src/app/plugins/kubernetes/components/infrastructure/nodes/selectors.ts

Only show hosts with kubernetes roles or unknown / no roles

UX-773/Do not show openstack hosts on kubernetes nodes list

---

src/api-client/ApiClient.ts
src/api-client/Hagrid.ts
src/api-client/Keystone.ts
src/app/constants.ts
src/app/core/containers/AppContainer.tsx
src/app/plugins/account/components/ssoManagement/SsoManagementPage.tsx
src/app/plugins/account/components/ssoManagement/groups/actions.ts
src/app/plugins/account/components/ssoManagement/sso/SsoEnabledDialog.tsx
src/app/plugins/account/components/ssoManagement/sso/SsoPage.tsx
src/app/plugins/account/components/ssoManagement/sso/SsoProviderPicklist.tsx
src/app/plugins/account/components/ssoManagement/sso/SsoToggle.tsx
src/app/plugins/account/components/ssoManagement/sso/UploadSamlMetadataLink.tsx
src/app/plugins/account/components/ssoManagement/sso/actions.ts

I didn't implement contextLoader in the actions here, might make sense to just not use it at all? Seems like a fast API and important to stay up-to-date. Thoughts?
Screenshots of some of the different screens below

UX-647/Added self-service SSO configuration

---

src/app/plugins/kubernetes/components/infrastructure/common/actions.js

we should not cache region data as when a new region is added the UI does not know to refetch that

UX-827/Don't cache regions

---

src/api-client/Clemency.ts
src/app/core/public/ActivateUserPage.tsx
src/app/core/public/ForgotPasswordPage.js
src/app/core/public/ResetPasswordPage.tsx
src/app/plugins/account/components/userManagement/users/actions.js

Tested on Pratik's testbed, user activation & reset password workflows working properly

UX-847/Update Clemency APIs for 5.1

---

src/app/plugins/kubernetes/components/infrastructure/clusters/import/ClustersChecklists.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ComingSoonDialog.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ImportAKSRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ImportEKSClusterPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/importGKERequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/DetachImportedClusterDialog.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/ToggleMonitoringDialog.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/header-card.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/selectors.ts

Added some tracking for imported clusters and some misc other fixes

Imported cluster tracking

---

src/app/plugins/kubernetes/components/infrastructure/clusters/import/ClustersChecklists.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ImportEKSClusterPage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/RegionsChecklist.tsx

UX-869/Expose error messages for discovered cluster regions

---

src/app/plugins/kubernetes/components/apps/deploy-app-page.tsx
src/app/plugins/kubernetes/components/apps/edit-app-deployment-page.tsx

UX-875/Changed upload .yaml file wording in deploy and edit deployed app forms

---

src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/custom.tsx

UX-874/Made API FQDN field in AWS and Azure cluster creation optional

---

src/app/core/components/BulletList.tsx
src/app/core/components/validatedForm/Info.tsx
src/app/plugins/kubernetes/components/infrastructure/InfrastructurePage.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-deployed-apps.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ImportAKSRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/ImportEKSRequirements.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/import/importGKERequirements.tsx
src/app/plugins/kubernetes/components/pods/AddResourcePage.js
src/app/plugins/kubernetes/index.js

UX-870, UX-881, UX-883, UX-896/copy updates, hide app catalog tabs, fix a bug on deployments

---

src/app/plugins/account/components/ssoManagement/sso/SsoPage.tsx
src/app/plugins/account/components/ssoManagement/sso/SsoProviderPicklist.tsx
src/app/plugins/account/components/ssoManagement/sso/model.ts

UX-813/Add other option to SSO provider dropdown

---

src/app/plugins/kubernetes/components/alarms/AlarmDetailsDialog.tsx
src/app/plugins/kubernetes/components/pods/renderLabels.js

UX-713/Fixed alarm dialog text overflow issue

---

src/app/core/containers/AppContainer.tsx
src/app/core/public/LoginPage.tsx

UX-893/Hide Terms of Service in Login Page if customer tier is OEM

---

src/app/plugins/kubernetes/components/virtual-machines/index.tsx
src/app/plugins/kubernetes/components/virtual-machines/kubevirt-landing-page.tsx
src/app/plugins/kubernetes/components/virtual-machines/list-page.tsx

forgot the empty page / null state for when kubevirt is not enabled

---

src/app/core/components/graphs/StackedAreaChart.tsx
src/app/core/helpers/createListTableComponent.js
src/app/plugins/kubernetes/components/alarms/TimePicklist.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-alarms.tsx

Note: this is based off of ux-304 bc there is some code in there I am making use of, would be easier to review after 303 is pushed in

UX-303/Added cluster details alarm tab

---

src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/cluster-alarms.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/imported-cluster-details.tsx
src/app/plugins/kubernetes/components/infrastructure/importedClusters/model.ts

Had to make a few changes to bridge the differences between the imported cluster details page & the normal cluster details page

Add alarms tab to imported cluster details

---

src/app/core/components/listTable/ListTable.js
src/app/core/helpers/createCRUDComponents.js
src/app/core/helpers/createListTableComponent.js
src/app/plugins/account/components/userManagement/tenants/UserRolesTableField.js
src/app/plugins/account/components/userManagement/users/TenantRolesTableField.js
src/app/plugins/account/components/userManagement/users/UsersListPage.js
src/app/plugins/kubernetes/components/app-catalog/deployed-apps/deployed-apps-list-page.tsx
src/app/plugins/kubernetes/components/app-catalog/repositories/repositories-list-page.tsx
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/CloudProvidersListPage.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterNodes.js
src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js
src/app/plugins/openstack/components/hosts/HostsListContainer.js

UX-812/Allow search on list tables on multiple properties

---

src/app/plugins/kubernetes/links.ts

New link:  https://docs.platform9.com/kubernetes/quickstart#supported-operating-systems

UX-929/Modified node prerequisites doc link

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-single-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-single-master.tsx
src/app/plugins/kubernetes/links.ts

change the bareosclusterhelp link for  virtual single master or physical single master. previously it was opening pmkclioverview  link

UX-764/add-bareos-single-master-docs

---

src/app/plugins/kubernetes/components/app-catalog/repositories/add-repository-page.tsx

UX-940/Replace whitespaces in repository names with underscores

---

src/app/plugins/account/components/ssoManagement/sso/SsoPage.tsx

Had to swap Progress and ValidatedForm nesting order

Fixed lack of padding between form field cards in sso wizard

---

src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
src/app/plugins/kubernetes/components/infrastructure/nodes/selectors.ts
src/app/plugins/kubernetes/components/pods/selectors.ts

cleaned up how we get the scoped endpoint and also removed the string interpolation that was unnecessary

UX-949/fix the log urls to use v3

---

src/app/plugins/account/components/ssoManagement/sso/SsoPage.tsx

UX-821/Add account upgrade popup for SSO feature

---

src/app/constants.ts
src/app/plugins/account/components/ssoManagement/sso/SsoPage.tsx

 UX-906/Expose uploaded metadata XML in a codemirror instead of not displaying it

---

src/app/plugins/kubernetes/components/infrastructure/cloudProviders/CloudProvidersListPage.js
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/model.ts
src/app/plugins/kubernetes/components/infrastructure/cloudProviders/selectors.ts

UX-998/Add imported clusters count to cloud providers table

---

src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-multi-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-single-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-multi-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-single-master.tsx
src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/topology-manager.tsx

UX-1002/BareOs Single and Multi-Master cluster forms: Wrap input fields in step 5 of wizard in a card

---

src/app/core/containers/AppContainer.tsx

**Context:**
App wouldn't load because we didn't handle the initialFeatures === null case

UX-1005/Handle initialFeatures === null case in AppContainer

---

src/app/core/components/PollingData.tsx
src/app/core/components/validatedForm/ListTableField.tsx
src/app/core/helpers/createCRUDComponents.js
src/app/plugins/kubernetes/components/rbac/profiles/actions.ts
src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
src/app/plugins/kubernetes/components/rbac/profiles/rbac-profiles-list-page.tsx
src/app/plugins/kubernetes/components/rbac/profiles/selectors.ts
src/app/plugins/kubernetes/datakeys.model.ts

Added more columns and polling to rbac profiles list page. Also fixed clusterRef for profile creation request body.

---

src/api-client/Appbert.ts
src/api-client/Keystone.ts
src/api-client/Qbert.ts
src/api-client/ResMgr.ts
src/app/core/components/Filter.tsx
src/app/plugins/kubernetes/components/apiAccess/ApiRequestHelper.tsx

Fix API Access url params issue

---

src/api-client/Qbert.ts
src/app/core/utils/routes.ts
src/app/plugins/kubernetes/components/rbac/profiles/actions.ts
src/app/plugins/kubernetes/components/rbac/profiles/delete-profile-bindings.tsx
src/app/plugins/kubernetes/components/rbac/profiles/deploy/deploy-rbac-profile-page.tsx
src/app/plugins/kubernetes/components/rbac/profiles/rbac-profiles-list-page.tsx
src/app/plugins/kubernetes/components/rbac/profiles/selectors.ts
src/app/plugins/kubernetes/index.js

Added rbac profile binding management wizard
