- package-lock.json
- package.json
Github started showing this security warning:
https://github.com/zkat/cacache/issues/124
This just bumps the version of the `ssri` module.  Looks like the only thing that was depending on it was `copy-webpack-plugin` and that is only used during build time so I'm not too worried about this, but still, nice to get rid of that warning from github.
> ssri security patch

- src/app/app.css
Added it to the css file instead of js because I assume that MuiThemeProvider theme needs to be defined outside of the component we try to use withStyles on.
Other way could be extracting _main-content div as its own react component. Which would be the better implementation?
> Added padding to main content div to account for navbar

- src/app/core/common/CRUDListContainer.js
- src/app/core/common/ListTable.js
- src/app/plugins/openstack/components/TenantsPage.js
- src/app/plugins/openstack/components/tenants/TenantsListContainer.js
- src/app/plugins/openstack/components/tenants/actions.js
- src/graphql/openstack/schemas/UserManagement.graphql
- src/graphql/openstack/schemas/userManagement.js
- src/openstack-simulator/context.js
- src/openstack-simulator/models/ActiveModel.js
- src/openstack-simulator/typedefs.graphql
A little more refactoring on the generic CRUD table stuff.  I made it so that it clears the selected items after items are deleted.  Before it would just keep the selection.
I also did some experimenting and figured out how to update the Apollo cache after the delete mutations.  It's a little verbose.  I couldn't find much documentation about it.  I'll see if I can create some helper utilities to clean it up a little bit more.
> Add tenant delete mutation

- src/app/core/common/EnhancedTableHead.js
- src/app/core/common/ListTable.js
- src/app/plugins/openstack/api/keystone.js
- src/app/plugins/openstack/components/ApiAccessPage.js
- src/app/plugins/openstack/components/api-access/ApiAccessList.js
- src/app/plugins/openstack/components/api-access/ApiAccessListContainer.js
- src/app/plugins/openstack/components/flavors/FlavorsListContainer.js
- src/app/plugins/openstack/index.js
- src/graphql/openstack/index.js
- src/graphql/openstack/schemas/serviceCatalog.graphql
- src/graphql/openstack/schemas/serviceCatalog.js
- src/server/context.js
- src/server/models/Catalog.js
- src/stories/api-access/fakeService.js
- src/stories/api-access/listApis.stories.js
One thing that may need to change:
Currently the service catalog is stored in state in the 'openstack' property. However, the service catalog stores services outside of openstack too, like qbert, so it should probably be moved up to root level. I need to work on something for the old codebase now but I wanted to send a review first. I haven't been able to completely work out all the details about the way state is stored just yet.
> Added service catalog to the simulator and UI

- package-lock.json
- package.json
Update `react-dom` from 16.2.0 to 16.4.0 to ensure material_ui will work right.
With version 16.2.0, modals of material_ui will be assigned a property of `visibility: hidden`, which will make popup, select and menu not work.
After switching to version 16.4.0, the following part are tested:
- `npm run test` all passed
- All existing pages work right as before.
- login page
- user/flavor page (including adding new elements)
- API page
- Other pages with no data
Add `@material-ui/core` and `@material-ui/icons`, while keeping the old version of the old versions.
> Update React-Dom and Add material-ui/icons.

- src/app/app.css
- src/app/core/common/ListTable.js
* Fix the position of TablePagination. It will stay at the right corner of table frame, even when the content is scrolled.
* Fix the `max-width` and `overflow-x` to prevent the page getting stretched horizontally when there are many columns.
> Fix small issues of ListTable

- src/app/plugins/kubernetes/index.js
Just commenting out the navigation item for K8s since we aren't using it yet and it's not implemented correctly.
> Remove Kubernetes clusters since it does not work

- src/server/middleware.js
Only `setActiveRegion` when we using the REST client.  Simulated route will error otherwise.
> Fix bug for client in simulated mode

- src/app/core/DataUpdater.js
- src/app/core/common/CRUDListContainer.js
- src/app/core/common/Checkbox.js
- src/app/core/common/ListTable.js
- src/app/core/common/Picklist.js
- src/app/core/common/PicklistField.js
- src/app/core/common/TextField.js
- src/app/core/common/ValidatedForm.js
- src/app/core/common/Wizard.js
- src/app/core/common/WizardStep.js
- src/app/core/fp.js
- src/app/plugins/openstack/components/volumes/AddVolumeForm.js
- src/app/plugins/openstack/components/volumes/AddVolumePage.js
- src/app/plugins/openstack/components/volumes/UpdateVolumeForm.js
- src/app/plugins/openstack/components/volumes/UpdateVolumePage.js
- src/app/plugins/openstack/components/volumes/VolumeTypesListPage.js
- src/app/plugins/openstack/components/volumes/VolumesList.js
- src/app/plugins/openstack/components/volumes/VolumesListContainer.js
- src/app/plugins/openstack/components/volumes/VolumesListPage.js
- src/app/plugins/openstack/components/volumes/actions.js
* Making some Higher Order Components (HOCs) to make CRUD based operations easier outside of GraphQL.
* Creating `<Picklist>` functionality since we don't have anything that works well in forms.
* Added custom `render` method support for Table `columnDef`s.
Currently this PR still needs some work on the Picklist and Volumes CRUD functionality.
> CRUD volumes refactoring

- src/app/core/common/Wizard.js
- src/app/plugins/openstack/components/volumes/AddVolumeForm.js
This contains some cleanup, fixes, and additional functionality for `<Wizard>` and `<WizardStep>`.
* Added a `submitLabel` to `<Wizard>` so the final "Complete" button can be customized.
* Automated the handling of `activeStepId` so the programmer does not need to worry about it anymore.
* Added a default `onComplete` handler.
* Renamed `context` and `setContext` to `wizardContext` and `setWizardContext` respectively to avoid naming collision with `withAppContext`.
* Slight refactoring to improve readability.
> Refactor Wizard and WizardStep

- src/app/core/DataUpdater.js
- src/app/core/common/KeyValuesField.js
- src/app/core/fp.js
- src/app/plugins/openstack/components/volumes/UpdateVolumeSnapshotForm.js
- src/app/plugins/openstack/components/volumes/actions.js
This PR adds metadata functionality to volume snapshots.  The `KeyValuesField` should make it easy to add this functionality to other forms.
> Allow snapshot metadata editing

- src/app/App.js
- src/app/core/AppContext.js
- src/app/core/common/CRUDListContainer.js
- src/app/core/fp.js
- src/app/plugins/openstack/components/SessionManager.js
- src/app/plugins/openstack/components/flavors/AddFlavorPage.js
- src/app/plugins/openstack/components/flavors/FlavorsListContainer.js
- src/app/plugins/openstack/components/flavors/actions.js
- src/app/plugins/openstack/components/sshkeys/AddSshKeyPage.js
- src/app/plugins/openstack/components/sshkeys/actions.js
- src/app/plugins/openstack/components/volumes/AddVolumePage.js
- src/app/plugins/openstack/components/volumes/AddVolumeTypePage.js
- src/app/plugins/openstack/components/volumes/actions.js
- src/openstack-client/Nova.js
Made some minor but significant improvements and fixes.
* `setContext` now returns a `Promise` if you do not pass in an async handler as the 2nd argument.
* Created utility `asyncForEach` that runs each callback in serial.  This is necessary to avoid race conditions when deleting multiple items and calling `setContext` after each delete.
* Fixed bug for adding a new flavor when user refreshes page on the `AddFlavorPage`.  *We will need to adopt this pattern in other places*—basically any add or update to a collection should first ensure the collection exists.
* Fixed `CRUDListContainer` to make `onRemove` "`await`".
* Added a loading notification when the app is first initializing.  This is necessary to prevent the login page from flashing temporarily.
* Refactored client to return …
> Misc random improvements and bugfixes

- .eslintrc
- src/app/core/createAddComponents.js
- src/app/core/createFormComponent.js
- src/app/plugins/openstack/components/flavors/AddFlavorPage.js
This makes it simpler to create simple AddForms.  With this approach we don't need as many `import` statements.  Additionally, this allows us to generate a larger portion of the UI dynamically from a spec.
This will work for the trivial use cases, but not for something with Wizards and Picklists that require loading data from external APIs (`AddVolumeForm`).  That will still require specifying a custom `FormComponent`.  However, as we see common patterns we can incorporate that into the `formSpec`.
> Simplify creating Add forms for trivial use case

- src/app/plugins/kubernetes/index.js
- src/app/plugins/openstack/index.js
The first release of the new UI will be Kubernetes only.
OpenStack will take much longer and will be released later so I'm commenting out the OpenStack clutter in the side nav.
> Hide OpenStack navigation for first release

- src/api-client/Qbert.js
- src/app/core/common/ListTable.js
- src/app/core/common/SimpleLink.js
- src/app/plugins/developer/components/ApiHelper.js
- src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/DownloadKubeConfigLink.js
- src/app/plugins/kubernetes/components/infrastructure/KubeCLI.js
- src/app/plugins/kubernetes/components/infrastructure/actions.js
This PR adds the Kubernetes Dashboard link as well as the CLI.
For the CLI I just used a `<Dialog fullScreen>` instead of the complex tab solution we have now.  The iTerm like tab solution might not be necessary and is a lot of custom code so I opted for the simpler solution for now.
I'm punting on the kubeconfig since I don't like saving the username / password in the client and re-using it.  We already have an auth mechanism so the backend should really provide a proper endpoint for this functionality.
> Cluster links

- package-lock.json
- src/app/plugins/openstack/components/users/actions.js
Nothing here really.  Turns out we never implemented `updateUser` so the build was complaining about it.
Also, `package-lock.json` was out of sync so I'm adding that as well.
> Suppress some warnings and upgrade package-lock

- src/app/core/common/ProgressBar.js
Just a quick fix to the propTypes for ProgressBar.  It wasn't accepting a React `node`.
> Fix for ProgressBar propTypes

- package-lock.json
- src/app/plugins/kubernetes/components/infrastructure/ClusterInfo.js
When a cluster is down we won't be able to get the version.  Show it as unavailable.  Also, update `package-lock.json` for the current `package.json`.
> Kubernetes version is not always available

- cypress/fixtures/example.json
- cypress/integration/clusters.spec.js
- cypress/integration/login.spec.js
- cypress/support/commands.js
- package.json
- src/server/main.js
* Created a mechanism to stub out the session so we don't have to log in on every single test.
* Created a hard-coded token that only works in the simulator that tests can use to bypass login.
There's some debate in my mind between making each test run independently and having previous tests be a prerequisite.  Using `cy.visit` on every test means we have to wait for the full page loads on every test.  I decided to make assumptions that the previous test ran in most of the tests to make tests run faster.
> Scaffold out how we can do integration tests

- cypress.json
- cypress/integration/clusters.spec.js
- cypress/support/commands.js
- package-lock.json
- package.json
- src/api-client/Qbert.js
- src/app/core/components/AnimateValues.js
- src/app/core/components/MoreMenu.js
- src/app/core/components/listTable/ListTable.js
- src/app/core/helpers/createListTableComponent.js
- src/app/plugins/kubernetes/components/infrastructure/ClusterAttachNodeDialog.js
- src/app/plugins/kubernetes/components/infrastructure/ClusterNodes.js
- src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/actions.js
- src/server/api/admin/index.js
- src/server/api/qbert/clusters/attachOperations.js
- src/server/api/qbert/index.js
- src/server/context/simulator.js
- src/server/main.js
- src/server/presets/dev.js
- src/server/server.js
This adds support for attaching nodes to a cluster.
There are also some misc bug fixes.
There is now an `/admin` API in the simulator to allow the server state to be controlled through an API.  This is used in the Cypress tests to allow state to be configured during test runs.  This is especially important in watch mode.
> Cluster actions (attach)

- src/app/core/components/ExternalLink.js
- src/app/plugins/kubernetes/components/infrastructure/AddClusterPage.js
- src/app/plugins/kubernetes/components/infrastructure/ClusterAttachNodeDialog.js
- src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/NodesListPage.js
This adds some consistency to our external links.  It also makes it so that `rel="noopener"` and `target="_blank"` get applied consistently.
If we use this component it will be easier to find external links and change how we link to them in the future.
> Refactor external links into their own component

- cypress/integration/clusters.spec.js
- src/api-client/Qbert.js
- src/app/plugins/kubernetes/components/infrastructure/ClusterDetachNodeDialog.js
- src/app/plugins/kubernetes/components/infrastructure/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/actions.js
This allows nodes to be detached from clusters through the row action menu.
> Detach nodes from clusters

- src/api-client/Keystone.js
- src/api-client/Qbert.js
- src/app/core/components/SimpleLink.js
- src/app/plugins/kubernetes/components/infrastructure/DownloadKubeConfigLink.js
- src/server/api/qbert/index.js
- src/server/api/qbert/kubeConfig/getKubeConfig.js
Had a few points I wanted to run by you guys:
1. We need some way to tell users that the kubeconfig will only work for 24 hours. Ideally this should go through a designer.
2. Wasn't sure if it'd be worth it to create a util function for creating a download. Currently this is our only use for this kind of functionality, although I could certainly see nice-to-have features that could use it (like a csv download of a list table for example)
> Added kubeconfig download link to clusters list

- src/api-client/Keystone.js
This error message was added because it can be useful during development but is preventing the app from initializing correctly in production environments where the initial region is not explicitly specified.  Looks like we can just eliminate this requirement completely and default to the keystone endpoint which has `/` instead of the FQDN by default.
> Do not require setActiveRegion during initialization

- src/app/core/components/Navbar.js
- src/app/core/utils/pluginManager.js
- src/app/plugins/kubernetes/index.js
- src/app/utils/__tests__/fp.test.js
- src/app/utils/fp.js
This redirects the current nav item links to the old clarity UI.
During development we can `window.localStorage.disableClarityLinks = true`.
This only works when clicking on nav links.  It does not redirect to Clarity on initial page loads.  We probably don't need to worry about this since it is going to be rare for people to bookmark pages on the new UI before it is fully ported.
> Redirect navItems to the old UI

- README.md
- src/app/App.js
- src/app/plugins/index.js
Turn it on for development using:
`window.localStorage.setItem('enableDevPlugin', true)`
> Hide the developer plugin by default

- package-lock.json
- src/app/plugins/openstack/components/tenants/TenantChooser.js
For some reason the intercom plugin was not included in the `package-lock.json`.
This also fixes the `TenantChooser` when the user has not selected a tenant in the past.
> Fix TenantChooser error when tenant not previously selected

- package-lock.json
- package.json
- src/api-client/Qbert.js
- src/app/core/components/Picklist.js
- src/app/core/components/validatedForm/KeyValuesField.js
- src/app/core/components/validatedForm/PicklistField.js
- src/app/core/components/validatedForm/ValidatedForm.js
- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusAlerts.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusMonitoringPage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRuleForm.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRulesTable.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
- src/app/plugins/kubernetes/index.js
- src/app/utils/fp.js
This is the first version of the Managed Prometheus solution.  Currently it is very alpha.  The backend will be changing to consolidate the API into 1 call instead of 4.
The way the API is currently structured we need to create 4 CRD objects (`prometheuses`, `servicemonitors`, `prometheusrules`, and `alertmanagers`) for each Prometheus Instance in the UI.  They are associated using the standard Kubernetes `labels` / `selector` paradigm.
The UI makes the assumption of a 1-to-1 relation between the different CRDs but that is not the case in the backend.  As a result, deleting is difficult because we don't know which objects to delete.
No simulator endpoints were created due to the fact that the API will be radically changing.
> Monitoring

- src/app/core/components/MoreMenu.js
Was getting `cond is not a function` so only calling it when it exists.
> Allow MoreMenu to work without passing cond

- package-lock.json
- package.json
`fsevents` is used for local development to watch the filesystem for changes.  It is not supported on Linux and is failing in TeamCity builds.  For some reason Travis is passing just fine.  It's an easy change to make it optional though so that's what this PR does.  In theory, this should resolve the TeamCity build failures.
> Make fsevents optional on Linux envs

- src/api-client/ApiClient.js
- src/api-client/Appbert.js
- src/api-client/Qbert.js
- src/app/core/components/AutocompleteBase.js
- src/app/core/components/CRUDListContainer.js
- src/app/core/components/listTable/ListTable.js
- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusAlertManagers.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusAlerts.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusMonitoringPage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRules.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusServiceMonitors.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
This PR implements Prometheus Monitoring for clusters that have Prometheus enabled.
The old UI should now have a checkbox to enable Prometheus monitoring when creating a cluster.
Once a cluster has prometheus on it, we show the Prometheus Instances, Service Monitors, AlertManagers, and PrometheusRules.
Creating a Prometheus Instance involves creating those custom resources used by the K8s Prometheus Operator.
Right now there is no way to delete or edit anything that is created.  That will come in future versions.
> Prometheus monitoring

- src/api-client/Qbert.js
- src/app/core/DataLoader.js
- src/app/core/components/CRUDListContainer.js
- src/app/core/helpers/createCRUDComponents.js
- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusAlertManagers.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRules.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusServiceMonitors.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
This PR updates the Managed Prometheus functionality to use the newer data loading abstractions.
This also adds delete capability for prometheus instances, rules, service monitors, and alert managers.
There seems to be a bug with `setContext` not refreshing the view.  Not sure why this is happening but it will need to be addressed in another PR.
> Delete prometheus objects

- src/api-client/ApiClient.js
- src/api-client/Qbert.js
- src/app/core/DataLoader.js
- src/app/core/components/KeyValues.js
- src/app/core/components/validatedForm/KeyValuesField.js
- src/app/core/components/validatedForm/ValidatedForm.js
- src/app/core/components/validatedForm/ValidatedFormDebug.js
- src/app/core/helpers/clusterContextLoader.js
- src/app/core/helpers/clusterContextUpdater.js
- src/app/core/helpers/contextLoader.js
- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRuleForm.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusRules.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusServiceMonitors.js
- src/app/plugins/kubernetes/components/prometheus/UpdatePrometheusInstancePage.js
- src/app/plugins/kubernetes/components/prometheus/UpdatePrometheusRulePage.js
- src/app/plugins/kubernetes/components/prometheus/UpdateServiceMonitorPage.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
- src/app/plugins/kubernetes/index.js
- src/app/utils/fp.js
This adds dashboard links and editing functionality for the different Prometheus Custom Resources for the Prometheus Operator.
The `contextUpdater` function seems buggy.  When I use it to perform a delete in `deletePrometheusRule` the context is updated but the table view does not refresh.
When I use `contextUpdater` to update a rule, it creates a `context[undefined]` entry instead of placing it in `context.prometheusRules`.
> Prometheus edit

- src/app/core/components/ExportDataButton.js
- src/app/core/components/ImportDataButton.js
- src/app/plugins/theme/components/ConfigureThemePage.js
- src/app/plugins/theme/components/ImportExportPanel.js
This PR creates an export button to allow the user to save the `theme.json` and a corresponding Import button to allow the user to load the previously saved theme.
> Import / Export theme.json

- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
- src/app/plugins/theme/index.js
Longer term we need to address data loading, caching, and scoping, but in the interest of the 3.11 release I am creating this workaround to unblock the Prometheus feature.
> Temp workaround for Prometheus cluster namespaces scoping issue

- src/app/core/DataLoader.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
- src/app/plugins/kubernetes/index.js
This PR makes the following changes:
* Make `Prometheus Monitoring (BETA)` sidenav item appear in the same location and the same text as the `Clarity` UI.
* Fix typo in `deletePrometheusInstance` where it was using `id` instead of `uid`.
* Fix `DataLoader` so it loads and updates its data using `context` instead of local `state`.  This fixes a bug where reloaded data was updated in the `context` but the view was not seeing the changes.
> Fix DataLoader refresh problem and misc Prometheus fixes

- src/app/App.js
- src/app/core/AppContext.js
- src/app/core/helpers/contextUpdater.js
- src/app/core/providers/ToastProvider.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
Most of the toasts need to happen inside of the `actions.js`.  Since actions are not components, there is no way to use `showToast` so I added it to the `context`.  This makes it very convenient to use.
I added toasts to the `create`, `update`, and `delete` prometheus actions.
> Add showToast to context and use in Prometheus

- src/app/ThemeManager.js
- src/app/core/components/AutocompleteBase.js
- src/app/core/components/Picklist.js
- src/app/core/components/SearchBar.js
- src/app/core/components/validatedForm/PicklistField.js
- src/app/core/components/validatedForm/TextField.js
Switches forms to use the `outlined` style for `Input` components.
This also removes some of the global theme overrides that messed up the styling for forms.  Looks like the previous styling was meant to target the `<SearchBar>` component in Tables so I made that styling specific to just that component.
> Use outlined style for form fields

- src/api-client/Qbert.js
- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
This removes the hard coding of the unit values (`Mi`, `Gi`, `d`, `w`, etc) from the values for things like memory, cpu, and storage.  Instead of being number fields, they are now just pure text fields.
There was too much inconsistency and we were fighting against how Kubernetes wants these values to be presented.  This simplifies the code, eliminates issues with unit type incompatibilities (`Mi` vs `Gi`), saves the UI from re-implementing the entire unit conversion system in Kubernetes, and provides the user more flexibility in choosing values.
The downside is that users must have more knowledge of the Prometheus operator and what these unit suffixes are.
After discussion we haven't come up with a good solution insulating the user from these unit suffix values—especially since they can …
> Make Prometheus Instance fields with unit values more flexible

- src/app/utils/__tests__/fp.test.js
- src/app/utils/fp.js
- src/server/api/appbert/clusters.js
- src/server/api/appbert/index.js
- src/server/api/qbert/index.js
- src/server/api/qbert/prometheus.js
- src/server/context/simulator.js
- src/server/models/openstack/Catalog.js
- src/server/models/prometheus/PrometheusInstance.js
- src/server/presets/dev.js
- src/server/server.js
This adds Managed Prometheus backend services to the simulator.
This PR only adds `PrometheusInstance`s.  Other endpoints will be added in a different PR.
Also did a slight refactor to the service catalog in the simulator since there was a ton of very verbose duplication.
> Add Managed Prometheus to simulator

- src/app/ThemeManager.js
- src/app/core/AppContext.js
- src/app/plugins/theme/components/ColorsPanel.js
- src/app/plugins/theme/components/CustomizeExpander.js
- src/app/plugins/theme/components/KitchenSink.js
- src/app/plugins/theme/components/examples/ButtonsExample.js
- src/app/static/theme.json
This adds a `theme.json` to our static files.  In the future we can override this file on the server to give different customers white-label theming capability.
I also sketched out an idea for providing the theme controls for the relevant section with the preview of it.  That way the person editing the theme isn't wondering what value needs to be changed to affect a given component.
> Load theme.json on app startup

- src/app/App.js
- src/app/core/AppContext.js
- src/app/core/components/CRUDListContainer.js
- src/app/core/helpers/clusterContextUpdater.js
- src/app/core/helpers/contextLoader.js
- src/app/core/helpers/contextUpdater.js
- src/app/core/helpers/createAddComponents.js
- src/app/core/helpers/createCRUDComponents.js
- src/app/plugins/openstack/components/volumes/AddVolumePage.js
- src/app/plugins/openstack/components/volumes/AddVolumeTypePage.js
- src/app/plugins/openstack/components/volumes/CreateSnapshotPage.js
- src/app/plugins/openstack/components/volumes/VolumeSnapshotsListContainer.js
- src/app/plugins/openstack/components/volumes/VolumesListContainer.js
This fixes an error that was causing the app to crash when displaying a toast notification, due to `ToastProvider` requiring the app theme but `ThemeManager` was being declared afterwards it so it was unable to access it.
Also fixed the deletion of list items as the context data was temporary emptied so it was misleading from the user perspective. Furthermore I added an overlayed loading spinner while a deletion is in progress so that the user will have a better feedback and he'll be unable to interact with the list until it has finished.
> Fix CRUDListContainer items adding and removal

- config.example.js
- src/app/plugins/kubernetes/index.js
When deploying the UI for demo / staging environments we don't want people needing to use the JavaScript console to set the `localStorage` settings.  This exposes it in the `config.js`.
I wanted to include it in `features.json` but unfortunately we need this information very early in the bootstrapping process and it would take too much effort and slow down initial app loading if we tried that approach.
> Enable public dev variant of UI

- package.json
- src/app/core/components/Toolbar.js
- src/app/core/components/buttons/CancelButton.js
- src/app/core/components/buttons/CreateButton.js
- src/app/core/components/buttons/NewEntryButton.js
- src/app/core/components/buttons/NextButton.js
- src/app/core/components/buttons/PrevButton.js
- src/app/core/components/buttons/SubmitButton.js
- src/app/core/components/listTable/ListTable.js
- src/app/core/components/listTable/ListTableToolbar.js
- src/app/core/components/listTable/PerPageControl.js
- src/app/core/helpers/createCRUDComponents.js
- src/app/plugins/developer/components/DeveloperToolsEmbed.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/theme/components/examples/ButtonsExample.js
- src/stories/common/buttons/CreateButton.stories.js
This PR makes the following changes:
* Created a set of buttons based on design feedback.  They are now added to the theme editor.  I tried adding them to Storybook as well but there are lots of issues with reloading and errors that I am leaning towards abandoning Storybook and just using the theme editor for showcasing components.
* Removed the title from the `ListTable`.  It has been decided not to have the title in the table itself.  Instead, any page that has a table will also have tabs—even when there is just 1 tab.
* Swapped out the "Create" button to the new design and added it to `createCRUDComponents`.
* Added the Rows Per Page control in the top right of the table.
* Made dev server listen on all address (needed for demo env since by default it is only `localhost`).
> Add buttons and misc design changes

- package-lock.json
Critical Vulnerability detected by npm: https://www.npmjs.com/advisories/1118
One of our dependencies had `eslint-utils` sub-dependency in a version with a known vulnerability.
This PR updates the version of `eslint-utils` to fix it.
> Fix dependency vulnerability issue

- src/app/core/components/MultiSelect.js
This PR:
- Apply styling to MultiSelect to make it look the old UI
- Changes `maxOptions` to no limit the number of options, but instead, it limits the component's height, but all the options could be viewed by scrolling.
TODO:
- Move some styling to `defaultTheme.js`
Storybook image
> [WIP] Style MultiSelect

- src/app/core/components/buttons/CreateButton.js
- src/app/plugins/kubernetes/components/logging/LoggingAddPage.js
- src/app/plugins/kubernetes/components/logging/LoggingEditPage.js
- src/app/plugins/kubernetes/components/logging/LoggingListPage.js
- src/app/plugins/kubernetes/index.js
This PR implements:
- Clicking on `+ New Logging` => Redirects to New Logging Page
- Clicking on `Edit` => Redirects to Edit Logging Page
> New Logging and Edit Logging empty pages

- src/api-client/Qbert.js
- src/app/core/components/listTable/ListTableBatchActions.js
- src/app/core/components/listTable/ListTableToolbar.js
- src/app/core/components/listTable/TitleAndAddButton.js
- src/app/core/helpers/createCRUDComponents.js
- src/app/plugins/kubernetes/components/logging/LoggingAddPage.js
- src/app/plugins/kubernetes/components/logging/LoggingEditPage.js
- src/app/plugins/kubernetes/components/logging/LoggingForm.js
- src/app/plugins/kubernetes/components/logging/LoggingListPage.js
- src/app/plugins/kubernetes/components/logging/LoggingStub.js
The main point in this PR is to refactor `Logging` to use helper methods and be prepared for the next step, that would be fetching and caching real data. More specifically, this PR:
- Creates `LoggingStub` to be used by `Qbert` while fetching real data is not implemented
- Refactor `LoggingListPage` to use helper method `createCRUDComponents`
- Refactor `LoggingAddPage` to use helper method `createAddComponents`
- Refactor `LoggingEditPage` to use helper method `createUpdateComponents`
- Creates `LoggingForm` to be used by `LoggingAddPage` and `LoggingEditPage`
- Refactor `createCRUDComponents` to support `batchActions`
- Refactor `ListTableBatchActions` to standardize custom batchActions buttons
> Use helper methods to create Logging pages: list, add and edit

- src/app/core/components/DebugProps.js
- src/app/core/components/MultiSelect.js
- src/app/core/components/Picklist.js
- src/app/core/components/validatedForm/PicklistField.js
- src/app/core/components/validatedForm/ValidatedForm.js
- src/app/plugins/kubernetes/components/infrastructure/AddAwsClusterPage.js
- src/app/plugins/kubernetes/components/infrastructure/AwsAvailabilityZoneChooser.js
- src/app/plugins/kubernetes/components/infrastructure/AwsRegionFlavorPicklist.js
- src/app/plugins/kubernetes/components/infrastructure/actions.js
- src/server/api/qbert/cloudProviders/getCpDetails.js
* Add field for choosing AWS Availability Zones
* Change `ValidatedForm` to also be able to accept a `renderProp`
* Added some other fields
* Added a cluster template preset picklist that to conveniently set multiple fields at once
> AWS Cluster Create AZs

- src/api-client/Qbert.js
- src/app/plugins/kubernetes/components/logging/actions.js
- src/server/models/qbert/Logging.js
This PR fixes the issue of trying to fetch loggings from an invalid cluster. It also adjusts the stubbed `getLoggings(clusterId)` to return an object instead of a list.
> Fix fetch loggings for invalid clusters

- src/app/plugins/kubernetes/components/prometheus/AddPrometheusInstancePage.js
The field name for specifying prometheus port and help message needs correction. The UI form hides ServiceMonitor object completely from the user. The user just
* specifies config for prometheus pod
* application labels and port from where metrics can be fetched
This change updates the field labels to reflect this design
> Fix metrics port label

- src/app/plugins/kubernetes/index.js
I'm just changing the conditional for right now in case we need to revert back.  Once we are more confident that we only want to stay within the new UI we can cleanup / remove the old links entirely.
> Remove old clarity links

- src/app/plugins/kubernetes/components/storage/StorageClassesAddPage.js
The backend expects strings for `true` and `false` instead of booleans in the Storage Class YAML. This PR fixes the front-end to meet this requirement.
> Return strings instead of booleans

- .gitignore
- decco-container/Dockerfile
- decco-container/Makefile
- decco-container/app_metadata.yaml
- decco-container/conf/confd/conf.d/cors-conf.toml
- decco-container/conf/confd/templates/cors.conf
- decco-container/conf/nginx/conf.d/pf9.conf
- decco-container/init-region
- decco-container/start.sh
- decco-container/y2j.py
- app name is pf9-serenity
- complies with decco/axon standard by supply an init-region script (which does nothing presently) and an app_metadata image annotation
- uses confd to set /etc/nginx/conf.d/pf9/cors.conf dynamically from Consul
- in order to build and push image, first run "make rpm" from support/ directory, then cd to decco-container/ and run "make push"
- required change in pf9-qbert repo: must add "admin_url" endpoint to Keystone at init-region time, the new UI needs it, whereas the old one uses "internal_url"
- testing: teamcity build: http://teamcity.platform9.horse:8111/viewLog.html?buildId=1034415&buildTypeId=Pf9project_ContainerBuilds_SerenityContainer&tab=buildResultsDiv, live UI: see https://du-test-kplane-leb-2568.platform9.horse/ui/
> decco container for next gen UI

- src/app/core/helpers/createContextUpdater.js
- src/app/core/hooks/useDataLoader.js
As a good practice, most of the data loading calls should be made in the `createFn`/`updateFn` of the createCRUDActions or `createContextUpdate` helpers.
To further encourage this, I added an additional parameter called `loadFromContext` so that we can cache-load any additional required data there:
Also please keep in mind that you can define any custom operations (besides create and update) with the already previously existing `customOperations` option:
These custom operations will also receive a third `loadFromContext` parameter from now on.
Moreover, I added the possibility of using `loadOnDemand` option in the `useDataLoader` hook which will allow us decide when to load the data instead of loading it when the component renders or on param updates. 
By doing so, we will be able to load …
> Added loadFromContext in create/update functions and loadOnDemand option in useDataLoader hook

- src/app/core/components/FormWrapper.js
- src/app/core/helpers/createContextLoader.js
- src/app/core/helpers/createContextUpdater.js
- src/app/plugins/kubernetes/components/apps/AppDetailsPage.js
- src/app/plugins/kubernetes/components/apps/actions.js
- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/actions.js
This will allow us to define composite unique identifiers such as
...instead of having to create a custom ID with the combined fields.
> Allow having composite unique identifiers when creating context loaders/updaters

- src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterSshKeyPicklist.js
Passing the correct props to component.
[](url)
> Fixed the SSH key field validation in AWS cluster creation wizard.

- package-lock.json
- src/app/core/components/listTable/ListTable.js
- src/app/core/components/listTable/ListTableHead.js
When the user is using the single radio selects in `ListTable` instead of the normal checkboxes the columns are off by 1.  This makes it so they are the same for both options.
> Fix bug where single select tables have columns misaligned

- package-lock.json
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
- src/app/plugins/kubernetes/index.js
This change fixes a few lables related to monitoring
* Prometheus Monitoring (beta) ==> Monitoring (beta). To make it consistent with logging tab
* Service Monitors ==> Service Monitor Selectors. To reflect correct type for data shown in the table. (Prometheus CR spec has a field called "Service Monitor Selector" which is what is shown here)
> Change prometheus labels

- src/app/plugins/kubernetes/components/prometheus/PrometheusServiceMonitors.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
This change removes the service monitor selector field from table view.
The selector field is of kubernetes API type: metav1.LabelSelector (https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitorspec)
which in itself can be of type MatchLabels or MatchExpressions (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#labelselector-v1-meta)
MatchLabels is simple key value array (which was handled)
MatchExpressions has operator format, which is more complex to display.
I believe for simplicity, we can omit this field from table view altogether.
> Remove service monitor selector field from table view

- src/api-client/Keystone.js
- src/api-client/ResMgr.js
- src/app/plugins/openstack/components/regions/RegionChooser.js
This fixes the confusing issue that happens when switching between servers, which tried to use the previously selected Region even if that region no longer existed.
However, it is not yet a perfect solution, as it is now, errors are still shown if a region is chosen without some required services (such as `qbert`)
I will address this other issue in another PR, after further discussing the possible solutions.
> Auto select first region if stored region doesn't exist

- src/app/core/components/Alert.js
- src/app/core/public/LoginPage.js
Debating whether or not to keep a separate component for smaller alerts? For this first pass, copied the entire Alert component and changed the styling. Could possibly add a prop that determines the size, but it could be possible these large and small alerts will diverge more in the future. Thoughts?
> [PMK-2186] Created smaller alert component for login failure alert

- src/app/core/helpers/createAddComponents.js
- src/app/core/utils/fieldValidators.js
- src/app/plugins/kubernetes/components/namespaces/AddNamespacePage.js
Added validation on the namespace field
Loading to the form wrapper for all createAddComponents.
Fixes PMK-2212
> Namespace form validation

- src/api-client/Appbert.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js
This change restores the "toggle prometheus" feature button in old UI.
Still working on the dialog actions, but sending out early change to ensure i am on the right track.
Clicking enable is supposed to call appbert service and enable prometheus package.
Similarly disable removes it.
> Monitoring addon button

- package-lock.json
- src/app/plugins/kubernetes/components/infrastructure/clusters/AddAwsClusterPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
Improved template chooser options for AWS and Azure cluster creation.
This adds a `custom` option to the picklist that conditionally renders the cluster configuration fields.
The config fields have all been moved into the first step, eliminating the need for the 2nd step entirely.
Address the following PR's:
* PMK-2192
* PMK-2257
> Add "custom" as a template choice option and move related fields to step1

- src/api-client/ApiClient.js
- src/app/core/components/CRUDListContainer.js
- src/app/core/components/toasts/ToastItem.tsx
- src/app/core/helpers/createContextLoader.js
- src/app/core/hooks/useDataLoader.js
- src/app/core/hooks/useDataUpdater.js
- src/app/plugins/kubernetes/components/apps/AddRepoDialog.js
Added an axios interceptor to return the server error messages instead of the generic javascript error, which then I show in the toast errors:
Also fixed the refresh of the tables after editing/add an item in the CRUD containers.
> [PMK-2196] Display server error messages in toast notifications

- src/app/plugins/kubernetes/components/infrastructure/nodes/actions.js
It turns out `loadNodes` is grabbing all its data from cached resources using `loadFromContext`, so even when we try to refetch the data, the data is being pulled out from the cache because `loadFromContext` doesn't refetch by default, unless either `refetchCascade` option is defined, or manually specifying so when calling `loadFromContext(cacheKey, params, refetch)` with `refetch = true`
> [PMK-2201] Force refetching of nodes when refreshing list

- src/app/core/components/ExternalLink.js
- src/app/core/helpers/createContextLoader.js
- src/app/plugins/kubernetes/components/apiAccess/endpoints/EndpointsListPage.js
- src/app/plugins/kubernetes/components/apiAccess/kubeConfig/KubeConfigListPage.js
- src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
- src/app/plugins/kubernetes/components/userManagement/users/actions.js
If the user doesn't have the required roles an empty array will be returned. This is just a life insurance as loaders that require this roles should not even be called in the first place (the routes are protected)
Unfortunately in some cases other loaders are used that reuse other loaders via `loadFromContext` function, that was the case in the Dashboard page where the users are being loaded, and as a side effect the credentials and tenants are being loaded to perform some extra logic that is just required in the user management section.
> Add requiredRoles option in context loaders

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
This PR adds `See details` action to clusters table
Card: https://platform9.atlassian.net/browse/PMK-2163
> Add See details action to cluster table

- src/api-client/ApiClient.js
- src/api-client/Keystone.js
- src/app/core/components/validatedForm/ValidatedForm.js
- src/app/core/helpers/createContextUpdater.js
- src/app/plugins/kubernetes/components/userManagement/users/TenantRolesTableField.js
* Fixed ValidatedForm to send just the values from defined fields instead of all the provided context
* (this is done to prevent overwriting wizard context with initial context values when navigating back and forth in the Wizard)
* Disable success fetch Toast notifications when performing update actions
* Refactor Keystone service to use singleton axios instance with our custom configuration (ttl, interceptors, etc)
> [PMK-2310] Fix ValidatedForm onSubmit handler and other issues

- src/app/core/components/validatedForm/ValidatedForm.js
- src/app/plugins/openstack/components/regions/RegionChooser.js
Fixed an issue on delayed field definition when the form is in active validation state (ie. the user has tried to submit the form) before all the fields defined in the form values have been added to it, which caused an uncaught exception and crashed the app with a white screen. 
To fix this I check the field existence in the form upon validation, and then I perform the validation when the field is defined (if the form is in validation state)
Example of the issue:
Also fixed warning caused by https://github.com/platform9/pf9-ui-plugin/pull/521:
> Form early validation issue

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
Hiding scale worker action for azure cloud provider type as backend work is not done yet.
> PMK-2321: Hiding scale worker action for azure cloud provider type as backend work is not done yet.

- src/app/core/helpers/createCRUDComponents.js
- src/app/plugins/kubernetes/components/prometheus/PrometheusInstances.js
This change customizes the no data text for monitoring list page.
Unlike other pages, monitoring  feature is not enabled by default.
When monitoring is enabled on a cluster, the backend deploys one prometheus instance for monitoring kubernets and worker nodes. Its absence indicates that monitoring feature is not properly enabled. 
This change also updates the add button text.
> Change instructions on monitoring page on no data

- src/app/plugins/kubernetes/components/common/CloudProviderCard.js
- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderPage.js
Looks like there was a regression where the `type` field got dropped from the cloud provider create action.
> PMK-2342 Fix for missing type in cloud provider create

- src/app/core/themes/defaultTheme.js
Quick fix for
This was caused by:
`theme.palette.status.card` was returning a rgba value instead of a hex
> Fix invalid hex error

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
- src/app/plugins/kubernetes/index.js
In preparation for launch, following features are to be disabled due to incompleteness
1. Monitoring tab
2. Logging tab and enable/disable button.
These features can be enabled after full CRUD featureset for it is implemented.
> Disable incomplete managed apps featureset

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
This PR:
- Renames ClusterNodes tabs to `Configuration` and `Nodes & Health Info`
- Clicking on `Connection Status` or `Health Status` redirects to `Nodes & Health Info`
> Link to cluster node details

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
This PR reimplements the way `Health Status` is calculated so that we don't use `numMasters` and `numWorkers` anymore. We had to do this because BareOS clusters don't have these properties filled.
> Reimplement health status to not use numMasters and numWorkers anymore

- src/app/plugins/theme/components/examples/TablesExample.js
- src/server/models/openstack/Token.js
- src/server/models/openstack/__tests__/Token.test.js
* Fixed the incorrect `useDataLoader` hook use by the `TablesExample` component
* Returning `expire_at` and `issued_at` fields in the authentication response to prevent instantly logging out the user upon login
> Fix login in simulator and theme manager

- src/app/plugins/kubernetes/components/infrastructure/nodes/actions.js
Already defined in `src/app/plugins/kubernetes/components/infrastructure/common/actions.js`
> Remove duplicated contextUpdater "updateRemoteSupport"

- src/app/core/helpers/createContextUpdater.js
- src/app/plugins/kubernetes/components/userManagement/tenants/actions.js
- src/app/plugins/kubernetes/components/userManagement/users/actions.js
* Changing default successful update/delete/create operation message to a more readable "XXX created successfully" instead of "Successfully created XXX"
* Customized success messages for update/delete/create operation messages of users/tenants to display the name of the updated user or tenant.
> PMK-2439 Change success update operations messages

- src/app/core/containers/AppContainer.js
Ran into this issue when working on another issue. If a user refreshed on the password reset page they would get kicked out to the login page.
> Allow paths to load as entry point when user is not logged in

- src/app/plugins/kubernetes/components/storage/AddStorageClassPage.js
Makes it so we only use storageTypes when they select an AWS cluster.  Otherwise they must specify their own provisioner manually.
> PMK-2533 Storage classes fixes

- src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
This fixes the issue with network plugin not being properly set when creating a new cluster:
> [PMK-2581] Fix network plugin field when creating a cluster

- package.json
- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AddCloudProviderPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/AddClusterPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/AwsClusterReviewTable.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/AzureClusterReviewTable.js
Remove disabled flag on azure options, format tags section in review tables like bareos, no need to lint when we test (save build time on each commit) since we lint + format on save as a pre-commit hook.
> PMK-2510, enable azure support

- src/app/core/PushEventManager.tsx
- src/app/core/providers/PushEventsProvider.tsx
This adds a 10 second delay and then retry when the websocket is closed.  Hopefully this won't hit the backend too hard.  If it turns out to be an issue we can add an exponential backoff.
This also fixes some misc issues with invalid message parsing.
> PushEvent retry and misc fixes

- src/app/core/components/InfoTooltip.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/AddAzureClusterPage.js
some tooltips overlay outside of a card when the last item. exposing the placement prop for the tooltip allows us to reposition tooltips conditionally
> expose placement for form field tooltips

- src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
- src/app/plugins/kubernetes/components/prometheus/actions.js
Mostly complete implementation of looking at tasks running on a cluster for `pf9-mon` package.
Not completely sure what the data mapper filtering is doing, probably need to update that to look for a task instead of the monitoring tag.
> Cluster install task for Prometheus

- src/app/core/components/KeyValues.js
- src/app/core/components/validatedForm/KeyValuesField.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/EditClusterPage.js
Hide the pf9-system:monitoring tag from the user bc the backend does not detect cluster label changes to enable/disable prometheus on clusters
> Hide the pf9-system:monitoring tag from the user

- deploy.bash
TeamCity populates branch as `<default>`. Not `master`.
> Fix default branch name

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDeleteDialog.tsx
we need to tell the event to `preventDefault` so that the form `onSubmit` doesn't fire the same delete call simultaneously
> dont make 2 requests on a delete

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
Adds the cluster UUID as an optional column.  It is disabled by default.  The user needs to click the gear icon to enable the `uuid` column.
Also threw in the `<CopyToClipboard>` functionality for convenience.
> Add UUID to ClusterListPage

- src/app/core/containers/AppContainer.js
- src/app/core/containers/AuthenticatedContainer.js
Not sure if that was the best spot to put it or if it should be in a more general spot. In the future, the login screen will also need to query features.json like this to know whether or not SSO is active. Could make more sense to put it into the component's state so that it can be passed to child components, but then calling restoreSession would need to be gated on the API and state being set.
> UX-232/Remove segment identify call for live demo DU

- src/app/core/containers/AuthenticatedContainer.js
The below button is confusing because we already have an `Add Cluster` button on the same page right below.  The button really asks them to sign up for Free Tier so we should word it accordingly.
Spoke with Madhura about the change already.
> UX-264/Make wording on Sandbox less confusing

- src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
- src/app/plugins/kubernetes/components/infrastructure/nodes/actions.js
If the node hostagent is not working, it seems that resmgr will report not responding while the nodes API may not know this information. So use the resmgr response to help determine the node status property.
> UX-89/Consider node as disconnected if resmgr is not responding for node

- src/app/plugins/kubernetes/components/userManagement/users/actions.js
Adding Segment events for when an admin creates another user and also when they invite another user.
We also want the invite associated with the actual invited user not the admin user but this can't be done cleanly in the UI so we are leaving the JIRA open and having the backend team add tracking to Clemency directly so that the `identify` calls can be associated correctly.
> PMK-3045 Segment user invite

- src/app/plugins/openstack/components/ironicSetup/IronicSetupPage.tsx
After ironic wizard refactor, didn't test on a fresh DU to catch this issue. Prob worth a backport to 4.4
> UX-507/Fixed ironic wizard loading issue if no networks present

- src/app/plugins/kubernetes/components/onboarding/PodSetup.tsx
Change Made:
- When PodSetup is loading pods, it will only render null on the first load.
> PodSetup does not return null on reloads

- src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
- src/app/utils/misc.js
Changes made:
- If a user has a displayname, the displayname will be displayed in the welcome header 
- If a user does not have a displayname, only 'Welcome!' will be displayed
> UX-241/Modified Welcome header message on dashboard

- src/app/plugins/kubernetes/components/pods/actions.js
Looks like the dashboard links were wrong. Want to check with backend too to make sure it's correct.
> UX-426/Fix kubernetes dashboard link for pods/deployments/services

- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/actions.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.js
Changes made:
- Aws -> AWS (Infrastructure tab)
- Amazon AWS Provider -> AWS Provider (Cloud providers tab)
- Hypervisor type is already removed in the node details page
- Cloud properties on Cluster details page 
AMI (already changed)
Domain Id -> Domain ID
Use Pf9 Domain -> Use PF9 Domain
Internal Elb (already changed)
AZs (already changed)
- Overview on Cluster details page
CloudProvider has already been changed to Cloud Provider
> UX-523/Modified labels on multiple screens

- src/app/core/components/progress/Progress.js
Fix issue of components not being rendered upon mounting if data has previously been loaded
> [UX-572] Cluster Details - Nodes page is blank for a very long time

- src/api-client/Qbert.ts
- src/api-client/qbert.model.ts
- src/app/core/components/progress/Progress.js
- src/app/core/helpers/createContextLoader.js
- src/app/core/hooks/useDataLoader.js
- src/app/plugins/kubernetes/components/alarms/AlarmsListPage.tsx
- src/app/plugins/kubernetes/components/alarms/actions.js
- src/app/plugins/kubernetes/components/alarms/selectors.ts
Added a `cache` option that is `true` by default but can be set to `false` to allow disabling the caching of the items so that they will always be fetched and replaced entirely in the redux store when using the `useDataLoader` hook, instead of "upserted".
Note that with `cache: false` option, data will be fetched and the store cached data replaced every time any of the `params` passed to the `useDataLoader` hook change, so beware of just updating those params when the data actually needs to be retrieved.
Whereas when using the `cache: true` option (the default) data will only be re-fetched and the store updated when the params defined by the `indexBy` option change.
> Add cache option and fix alerts page

- src/app/core/components/Navbar.js
- src/app/core/containers/AppContainer.tsx
Changes Made:
1. Added segment analytics.identify() before login with no UUID provided in order to enable Appcues
2. Intercom chat has already been removed so no additional changes were made
3. For both Sandbox and Decco DU, the UI toggle button to the old UI has been removed
4. Drift chat box is already present so no additional changes were made
> UX-432/Added flags for sandbox

- src/app/plugins/kubernetes/components/dashboard/DashboardPage.tsx
The current onboarding workflow is not very useful and we're seeing a lot of users never see the actual dashboard because they are always on onboarding.
> UX-615/remove the onboarding workflow

- src/app/plugins/kubernetes/components/common/CloudProviderRegionPicklist.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/one-click.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/azure/AddAzureClusterPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/azure/azure-availability-zone.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/custom.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/azure/create-templates/one-click.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/existing-network.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/master-node-instance-type.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/master-node-sku.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/master-node-subnet.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/resource-group.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/ssh-key-picklist.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/worker-node-instance-type.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/worker-node-sku.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/worker-node-subnet.tsx
When creating a custom Azure cluster,  existing networks are now shown in the Networks Configuration step.
The bug was related to Azure's display and region name mapping
> UX-683/Fixed Azure RegionName and DisplayName bug

- src/app/core/components/FontAwesomeIcon.tsx
- src/app/core/components/notifications/NotificationsPage.tsx
- src/app/core/components/notifications/NotificationsPopover.tsx
- src/app/core/hooks/useDataLoader.js
- src/app/core/hooks/useDataUpdater.js
- src/app/core/notifications/notificationReducers.ts
- src/app/core/utils/routes.ts
- src/app/plugins/kubernetes/components/prometheus/PrometheusAddonDialog.js
- src/app/plugins/kubernetes/index.js
- src/app/plugins/openstack/components/ironicSetup/AuthorizeHostStep.tsx
- src/app/plugins/openstack/components/ironicSetup/BareMetalNetworkStep.tsx
- src/app/plugins/openstack/components/ironicSetup/BareMetalSubnetStep.tsx
- src/app/plugins/openstack/components/ironicSetup/ControllerConfigStep.tsx
- src/app/plugins/openstack/index.js
Since toast notifications are removed, global errors will be shown in a popover on the top for 5 seconds:
If you click on the inbox icon you will be redirected to the notifications page:
> UX-627/Remove toast notifications and show inbox icon in the header

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
Changes Made:
- Scaling workers for Azure autoscaling clusters has been disabled
- A disabled info message now shows up for autoscaling clusters and for busy clusters. "Scaling Azure autoscaling clusters is not yet supported"  and "Cannot scale workers: cluster is busy"
> UX-720/Disabled scaling workers for Azure autoscaling clusters

- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AwsCloudProviderVerification.tsx
- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/AzureCloudProviderVerification.tsx
- src/app/plugins/kubernetes/components/infrastructure/cloudProviders/UpdateCloudProviderPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/ssh-key-picklist.tsx
What caused the bug:
- The cloud provider type wasn't passed to the region picklist component, so it defaulted to show the DisplayName, which is not available for AWS regions
Changes Made:
- Reused some cluster form components in the update cloud provider page
- Cloud provider type is now passed into the region picklist
> UX-717/Fixed AWS regions not showing in update cloud provider page

- src/app/plugins/kubernetes/components/apiAccess/kubeConfig/DownloadKubeConfigForm.js
- The username and password input field is now bigger and fills up the rest of the form
- When a user hits enter, the download kubeconfig button will get triggered. (This was already implemented)
> UX-636/Made username and password field for KubeConfig download form bigger

- src/app/plugins/kubernetes/components/pods/PodsListPage.js
- src/app/plugins/kubernetes/components/pods/selectors.ts
- Added a links column to the pods list table
- Added 'View Container Logs' link to the links column
When "View Container Logs' is clicked, a new window will open showing the logs
> UX-599/Added 'View Container Logs' option to Pods List Table

- src/app/core/components/DownloadHostAgentWalkthrough.tsx
- src/app/plugins/kubernetes/components/infrastructure/nodes/download-host-agent-page.tsx
- src/app/plugins/openstack/components/ironicSetup/IronicSetupPage.tsx
Added Linux and Ubuntu download options to the Onboard Node Advanced page
> UX-739/Added OS options for host agent download

- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/BareosClusterRequirements.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/InsufficientNodesDialog.tsx
A dialog now shows up when there are insufficient nodes for BareOs cluster creation.
> UX-742/Fixed logic for showing insufficient nodes dialog

- src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleMastersPage.tsx
User can now add a master node to an empty multi-master BareOs cluster. We have constraints already in place where a user cannot scale a cluster without a VIP, meaning that it must be a multi-master cluster. Not sure if we should remove this constraint for empty clusters.
I tried testing this out as best as I could, but I had to disable a lot of stuff. Our current UI does not even allow us to create an empty cluster. Also, my empty cluster was not healthy and its status was disconnected so I had to remove the healthy cluster constraint in order to scale it. I'm not sure if that was just my cluster or  if all empty clusters would be unhealthy as well.
> UX-733/Allow user to add master node to an empty BareOs cluster

- src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleMastersPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/ScaleWorkersPage.tsx
- **Nodes must now be connected in order to be attached to a BareOs cluster.**
- **Worker nodes can now only be scaled one at a time, just like master nodes**
ui-dev-master is disconnected so it should not show up in the node chooser
> UX-675/Only allow connected nodes to be attached to a BareOs cluster and nodes can only added one at a time

- src/app/core/components/DocumentMeta.tsx
- src/app/core/containers/AppContainer.tsx
A bug occurs when you login, logout, then login again. When `createSegmentScript()` and `createDriftScript() ` runs for the 2nd time, it returns `undefined` since the segment script already exists. When you try to add `undefined` to the DOM body, an exception occurs.
> Fixed Segment and Drift bug during login

- src/app/plugins/kubernetes/components/pods/PodsListPage.js
- src/app/plugins/kubernetes/components/pods/selectors.ts
Added a new 'containers' column to the pods list table that lists out the container names and the links to view the logs for the containers
> UX-761/Support viewing logs for pods with multiple containers

- src/app/plugins/account/components/userManagement/users/UsersListPage.js
- src/app/plugins/account/components/userManagement/users/actions.js
- src/app/plugins/account/components/userManagement/users/enable-disable-user-dialog.tsx
**NOTE:**
- 'Enable' and 'Disable' actions are disabled for the active user, meaning that you cannot enable or disable yourself.
> UX-779/Allow admin users to enable/disable other users in the users table and automatically enable a disabled user when changing their password

- src/api-client/Qbert.ts
- src/app/plugins/kubernetes/components/infrastructure/importedClusters/actions.ts
Would be good to add the typing for the new API endpoint. What tool do you use to auto-generate the models?
> Check sunpike API before making imported cluster requests

- src/app/plugins/kubernetes/components/pods/AddResourcePage.js
**Issue:**
On first load when the first cluster is automatically selected, the `clusterId` was not being added into the params. That's why the `NamepsacePicklist` field was disabled.
> UX-787/Added clusterId as a defaultParam in AddResourceForm

- src/api-client/Qbert.ts
- src/app/plugins/kubernetes/components/pods/DeploymentsListPage.js
- src/app/plugins/kubernetes/components/pods/actions.js
- src/app/plugins/kubernetes/components/pods/delete-deployment-dialog.tsx
**NOTES:**
- Namespaces in these protected namespaces cannot be deleted by the user: 
- platform9-system
- kube-system
- pf9-olm
- pf9-operators
- pf9-monitoring
> UX-440/Allow deployments to be deleted

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatusUtils.ts
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/model.ts
- src/app/plugins/kubernetes/components/infrastructure/clusters/selectors.ts
**NOTES:** 
- Cluster upgrade availability is no longer part of the cluster health status
- Cluster upgrade availability is now shown as a link in the K8s Version column in the clusters list table
- Link action has changed. Instead of going to the nodes details page, it will now open up the cluster upgrade dialog.
Since it's no longer part of cluster health, 'Upgrade Available' will no longer show up in the cluster status card.
> UX-762/Removed cluster upgrade availability out of cluster health status

- src/app/plugins/kubernetes/components/common/HelpPage.tsx
- src/app/plugins/kubernetes/links.ts
**NOTES:**
- A 'Submit a Support Request' tile has been added in the help page
- It links to the PF9 request form (https://support.platform9.com/hc/en-us/requests/new?ticket_form_id=360000924873)
- This will only show for  Growth and Enterprise customers
> UX-889/Added 'Submit a Support Request' tile in the Help Page

- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
When the user chooses a cluster template in the AWS cluster creation form, the template values are now properly updated
https://user-images.githubusercontent.com/23369276/117504734-ca7a3200-af37-11eb-8037-e149f77dc456.mov
> UX-931/Fixed AWS cluster template bug

- src/app/core/containers/AppContainer.tsx
In features.json, if `airgapped === true,` don't add the Segment script
> UX-905/Prevent sending data to Segment for airgapped environments

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterInfo.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
- src/app/plugins/kubernetes/components/infrastructure/nodes/NodeDetailsPage.tsx
**Changes:**
- Added ETCD Backup card to cluster details page that displays the following info:
- ETCD Backup: Enabled or Not Enabled (Required)
- Task Status
- ETCD Backup Storage Path
- ETCD Backup Interval
- ETCD Data Directory (required)
- ETCD Version
- Removed ETCD Backup related fields from the Overview card
- Fixed the InfoCard styling
> UX-226/Add ETCD Backup card to cluster details page

- src/app/plugins/kubernetes/components/infrastructure/clusters/actions.js
**Bug Description:**
After scaling down worker nodes for an AWS cluster, the node count in the clusters list table did not accurately reflect the number of nodes in the cluster. 
My cluster, kim-test, had 1 master node and 5 workers nodes. After scaling it down to 1 worker node and waiting for the cluster to finish updating, the clusters table still showed 6 nodes for my cluster even though the nodes api response shows only 2.
I noticed when refetching the nodes, we were doing `upsertAll` with the data in the cache. That's why the old nodes still remained
**Fix:**
When we fetch nodes for the clusters, we should pass `refetch = true` to `loadNodes` so that we do a `replaceAll` instead of `upsertAll` with the data
> UX-945/Fix bug where when scaling down a cluster, the old nodes still show up

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterStatus.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/ClustersListPage.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
- src/app/plugins/kubernetes/components/infrastructure/nodes/NodesListPage.js
- src/app/plugins/kubernetes/components/infrastructure/nodes/helper.ts
**Changes:**
- 'Node Clock Drift' status is added under cluster health column. Links to the cluster nodes list table
-  'Node Clock Drift' status is added under node health column. Links to the node details page
- Cluster upgrade is disabled if clock drift is detected
> UX-315/Add 'Node Clock Drift' status in cluster and node health status and prevent cluster upgrades if clock drift detected

- src/app/core/components/validatedForm/radio-fields.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/custom.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-multi-master.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-one-click.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/physical-single-master.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-multi-master.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-one-click.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/bareos/create-templates/virtual-single-master.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/form-components/node-registration-chooser.tsx
- src/app/plugins/kubernetes/components/infrastructure/clusters/helpers.ts
**Background:**
A new `useHostname` field has been added to cluster creation API. This parameter is ignored when deploying clusters on public clouds - AWS, Azure. and when deploying bare OS IPv6 clusters.
**Changes:**
- Added a new section called "Node Registration" on step one of BareOS VM and Physical single and multi-master cluster wizards with a radio toggle field that allows users to setup their cluster using hostname or IP address
- `useHostname` flag is defaulted to false for BareOs one-click clusters
- If IPv6 is chosen, the 'Use Node Hostname' field is disabled and the useHostname flag is automatically set to false
https://user-images.githubusercontent.com/23369276/118024952-20721f80-b314-11eb-90fd-a90b6b57ec51.mov
- Info message is shown when you hoover over the 'Use Node …
> UX-909/Add BareOS "useHostname" Flag during cluster create

- src/api-client/ApiClient.ts
**Issue:**
If login fails, we're exposing users' passwords in Bugsnag under the API URL tab
**Fix:**
Replace the users' passwords with `SENSITIVE_DATA_REMOVED`
`error.response.config.data ` is a JSON string so I converted into an object to replace the password with `SENSITIVE_DATA_REMOVED` and then converted it back to to a string
> Bugsnag: Remove user password from error.config.data

- src/app/plugins/kubernetes/components/infrastructure/clusters/aws/create-templates/one-click.tsx
**Issue:**
Creating an AWS cluster without a `domainId` in the one-click form results in an error from the API. This shouldn't happen because `domainId` field is not required
**Fix:**
`domainId` is required by the API but can be an empty string so default it to an empty string
> UX-995/Default domainId to empty string in AWS one-click cluster form

- src/app/plugins/kubernetes/components/infrastructure/clusters/ClusterDetailsPage.js
> UX-986/updated nodes list page to span entire screen
